import { createModule } from './moduleFactory';
import type { Exercise } from '../types';

const lessonExercises: Exercise[] = [
    {
    id: 'b2-05-ex-01',
    moduleId: 'b2-05',
    lessonId: 'b2-05-l1',
    type: 'multiple-choice',
    prompt: 'Core theme of this module?',
    explanation: 'Theme recognition.',
    skill: 'vocabulary',
    difficulty: 2,
    options: ['narrative', 'Only alphabet', 'Only numbers', 'Cooking recipes'],
    acceptedAnswers: ['narrative'],
  },
    {
    id: 'b2-05-ex-02',
    moduleId: 'b2-05',
    lessonId: 'b2-05-l1',
    type: 'fill-blank',
    prompt: '_____ ik meer tijd had, zou ik helpen.',
    explanation: 'Conditional als-clause.',
    skill: 'grammar',
    difficulty: 2,
    acceptedAnswers: ['Als'],
  },
    {
    id: 'b2-05-ex-03',
    moduleId: 'b2-05',
    lessonId: 'b2-05-l1',
    type: 'sentence-order',
    prompt: 'Order',
    explanation: 'Conditional zou.',
    skill: 'grammar',
    difficulty: 2,
    acceptedAnswers: ['Ik zou het anders aanpakken.'],
    orderItems: ['zou', 'Ik', 'het', 'anders', 'aanpakken', '.'],
  },
    {
    id: 'b2-05-ex-04',
    moduleId: 'b2-05',
    lessonId: 'b2-05-l1',
    type: 'listening',
    prompt: 'Pick the word',
    explanation: 'Listening recognition.',
    skill: 'listening',
    difficulty: 2,
    audioText: 'perspectief',
    options: ['perspectief', 'fiets', 'soep', 'stoel'],
    acceptedAnswers: ['perspectief'],
  },
    {
    id: 'b2-05-ex-05',
    moduleId: 'b2-05',
    lessonId: 'b2-05-l1',
    type: 'translation-en-nl',
    prompt: 'Translate: Er was een flashback',
    explanation: 'Target phrase.',
    skill: 'writing',
    difficulty: 3,
    acceptedAnswers: ['Er was een flashback'],
  },
    {
    id: 'b2-05-ex-06',
    moduleId: 'b2-05',
    lessonId: 'b2-05-l2',
    type: 'fill-blank',
    prompt: '_____ de tekst kritisch.',
    explanation: 'Imperative / instruction.',
    skill: 'grammar',
    difficulty: 2,
    acceptedAnswers: ['Lees', 'lees'],
  },
    {
    id: 'b2-05-ex-07',
    moduleId: 'b2-05',
    lessonId: 'b2-05-l2',
    type: 'error-correction',
    prompt: 'Fix: Ik zou hebben het gedaan gisteren.',
    explanation: 'Participle placement in conditional perfect.',
    skill: 'grammar',
    difficulty: 3,
    acceptedAnswers: ['Ik zou het gisteren hebben gedaan.', 'Ik zou het hebben gedaan.'],
  },
    {
    id: 'b2-05-ex-08',
    moduleId: 'b2-05',
    lessonId: 'b2-05-l2',
    type: 'reading-comp',
    prompt: 'Focus?',
    explanation: 'Topic in passage.',
    skill: 'reading',
    difficulty: 3,
    passage: 'In dit B2-onderdeel oefenen we narrative. Let op structuur en nuance.',
    options: ['narrative', 'spelling only', 'numbers', 'greetings'],
    acceptedAnswers: ['narrative'],
  },
    {
    id: 'b2-05-ex-09',
    moduleId: 'b2-05',
    lessonId: 'b2-05-l2',
    type: 'matching',
    prompt: 'Match',
    explanation: 'B2 keywords.',
    skill: 'vocabulary',
    difficulty: 2,
    acceptedAnswers: ['beleid=policy', 'bewijs=evidence', 'ambitie=ambition'],
    pairs: [{ left: 'beleid', right: 'policy' }, { left: 'bewijs', right: 'evidence' }, { left: 'ambitie', right: 'ambition' }],
  },
    {
    id: 'b2-05-ex-10',
    moduleId: 'b2-05',
    lessonId: 'b2-05-l2',
    type: 'guided-writing',
    prompt: 'Write a short B2 paragraph about narrative.',
    explanation: 'Self-assess.',
    skill: 'writing',
    difficulty: 3,
    modelAnswer: 'Wat narrative betreft, vind ik dat nuance en bewijs essentieel zijn. Bovendien helpt reflectie om betere keuzes te maken.',
    checklist: ['On topic', 'Uses at least one advanced connector', 'Clear conclusion'],
  }
];

const checkpoint: Exercise[] = [
    {
    id: 'b2-05-ex-11',
    moduleId: 'b2-05',
    type: 'multiple-choice',
    prompt: 'B2 writing should…',
    explanation: 'Argument quality.',
    skill: 'writing',
    difficulty: 2,
    options: ['support claims with reasons', 'only list words', 'avoid connectors', 'use only A1 phrases'],
    acceptedAnswers: ['support claims with reasons'],
  },
    {
    id: 'b2-05-ex-12',
    moduleId: 'b2-05',
    type: 'fill-blank',
    prompt: '_____ de bronnen betrouwbaar zijn, kun je citaten gebruiken.',
    explanation: 'Condition.',
    skill: 'grammar',
    difficulty: 2,
    acceptedAnswers: ['Mits', 'Als'],
  },
    {
    id: 'b2-05-ex-13',
    moduleId: 'b2-05',
    type: 'listening',
    prompt: 'Connector?',
    explanation: 'Moreover.',
    skill: 'listening',
    difficulty: 2,
    audioText: 'Bovendien is het goedkoper',
    options: ['Bovendien', 'Misschien', 'Hallo', 'Doei'],
    acceptedAnswers: ['Bovendien'],
  },
    {
    id: 'b2-05-ex-14',
    moduleId: 'b2-05',
    type: 'reading-comp',
    prompt: 'Tone?',
    explanation: 'Critical reading.',
    skill: 'reading',
    difficulty: 3,
    passage: 'Het artikel klinkt stellig, maar het bewijs is dun. Een kritische lezer vraagt om bronnen.',
    options: ['critical', 'celebratory', 'silent', 'childish'],
    acceptedAnswers: ['critical'],
  },
    {
    id: 'b2-05-ex-15',
    moduleId: 'b2-05',
    type: 'guided-writing',
    prompt: 'Respond to a short prompt on narrative in 5 sentences.',
    explanation: 'Self-assess.',
    skill: 'writing',
    difficulty: 3,
    modelAnswer: 'Mijn standpunt over narrative is genuanceerd. Enerzijds zie ik voordelen. Anderzijds zijn er risico\'s. Daarom stel ik een stapsgewijze aanpak voor.',
    checklist: ['Standpunt', 'Two sides or concession', 'Conclusion'],
  }
];

export const moduleB205 = createModule(
  {
    id: 'b2-05',
    level: 'b2',
    title: 'Complex stories and perspective',
    titleNl: 'Complexe verhalen',
    topic: 'narrative',
    grammarFocus: ['Perspective shifts', 'Past vs perfect choices', 'Impliciet/expliciet'],
    vocabularyFocus: ['perspectief', 'spanningsboog', 'flashback'],
    skills: ['reading', 'writing', 'listening', 'grammar'],
    description: 'Follow and retell multi-layered narratives with clear perspective.',
    order: 29,
  },
  [
    {
      id: 'b2-05-l1',
      title: 'Tracking perspective',
      objective: 'Identify whose viewpoint a text uses.',
      steps: [
        {
          type: 'explanation',
          title: 'Who is telling, and what is hidden?',
          body: 'B2 stories may shift perspectief or use a flashback. Notice what is impliciet versus expliciet. Summarise events without inventing facts.',
        },
        {
          type: 'examples',
          title: 'In context',
          items: [
            { nl: 'Vanuit haar perspectief voelde de reis onveilig.', en: 'From her perspective the journey felt unsafe.' },
            { nl: 'De flashback verklaart zijn twijfel.', en: 'The flashback explains his doubt.' }
          ],
        },
        {
          type: 'vocabulary',
          title: 'Key words',
          vocabularyIds: ['vocab-b2-450', 'vocab-b2-451', 'vocab-b2-452', 'vocab-b2-453', 'vocab-b2-454', 'vocab-b2-470'],
        },
        {
          type: 'exercise',
          exerciseIds: ['b2-05-ex-01', 'b2-05-ex-02', 'b2-05-ex-03', 'b2-05-ex-04', 'b2-05-ex-05'],
        },
        {
          type: 'summary',
          title: 'Quick recap',
          bullets: ['Name the narrator/viewpoint', 'Separate facts from hints'],
        },
      ],
    },
    {
      id: 'b2-05-l2',
      title: 'Retelling with control',
      objective: 'Retell a short story with a clear arc.',
      steps: [
        {
          type: 'explanation',
          title: 'Spanningsboog',
          body: 'Mark begin, turning point, and ending. Choose tense consistently; mix only when the narrative needs a flashback.',
        },
        {
          type: 'examples',
          title: 'In context',
          items: [
            { nl: 'Eerst leek alles rustig; uiteindelijk barstte het conflict los.', en: 'At first everything seemed calm; eventually the conflict erupted.' },
            { nl: 'De spanningsboog houdt de lezer vast.', en: 'The narrative arc holds the reader.' }
          ],
        },
        {
          type: 'vocabulary',
          title: 'Key words',
          vocabularyIds: ['vocab-b2-452', 'vocab-b2-470', 'vocab-b2-450', 'vocab-b2-451', 'vocab-b2-453', 'vocab-b2-454'],
        },
        {
          type: 'exercise',
          exerciseIds: ['b2-05-ex-06', 'b2-05-ex-07', 'b2-05-ex-08', 'b2-05-ex-09', 'b2-05-ex-10'],
        },
        {
          type: 'summary',
          title: 'Quick recap',
          bullets: ['Keep a clear arc', 'Signal flashbacks explicitly'],
        },
      ],
    }
  ],
  lessonExercises,
  checkpoint,
);

export const moduleB205Exercises = lessonExercises;
