import { createModule } from './moduleFactory';
import type { Exercise } from '../types';

const lessonExercises: Exercise[] = [
    {
    id: 'b2-06-ex-01',
    moduleId: 'b2-06',
    lessonId: 'b2-06-l1',
    type: 'multiple-choice',
    prompt: 'Core theme of this module?',
    explanation: 'Theme recognition.',
    skill: 'vocabulary',
    difficulty: 2,
    options: ['future scenarios', 'Only alphabet', 'Only numbers', 'Cooking recipes'],
    acceptedAnswers: ['future scenarios'],
  },
    {
    id: 'b2-06-ex-02',
    moduleId: 'b2-06',
    lessonId: 'b2-06-l1',
    type: 'fill-blank',
    prompt: '_____ ik meer tijd had, zou ik helpen.',
    explanation: 'Conditional als-clause.',
    skill: 'grammar',
    difficulty: 2,
    acceptedAnswers: ['Als'],
  },
    {
    id: 'b2-06-ex-03',
    moduleId: 'b2-06',
    lessonId: 'b2-06-l1',
    type: 'sentence-order',
    prompt: 'Order',
    explanation: 'Conditional zou.',
    skill: 'grammar',
    difficulty: 2,
    acceptedAnswers: ['Ik zou het anders aanpakken.'],
    orderItems: ['zou', 'Ik', 'het', 'anders', 'aanpakken', '.'],
  },
    {
    id: 'b2-06-ex-04',
    moduleId: 'b2-06',
    lessonId: 'b2-06-l1',
    type: 'listening',
    prompt: 'Pick the word',
    explanation: 'Listening recognition.',
    skill: 'listening',
    difficulty: 2,
    audioText: 'beleid',
    options: ['beleid', 'fiets', 'soep', 'stoel'],
    acceptedAnswers: ['beleid'],
  },
    {
    id: 'b2-06-ex-05',
    moduleId: 'b2-06',
    lessonId: 'b2-06-l1',
    type: 'translation-en-nl',
    prompt: 'Translate: De vooruitzichten zijn goed',
    explanation: 'Target phrase.',
    skill: 'writing',
    difficulty: 3,
    acceptedAnswers: ['De vooruitzichten zijn goed'],
  },
    {
    id: 'b2-06-ex-06',
    moduleId: 'b2-06',
    lessonId: 'b2-06-l2',
    type: 'fill-blank',
    prompt: '_____ de tekst kritisch.',
    explanation: 'Imperative / instruction.',
    skill: 'grammar',
    difficulty: 2,
    acceptedAnswers: ['Lees', 'lees'],
  },
    {
    id: 'b2-06-ex-07',
    moduleId: 'b2-06',
    lessonId: 'b2-06-l2',
    type: 'error-correction',
    prompt: 'Fix: Ik zou hebben het gedaan gisteren.',
    explanation: 'Participle placement in conditional perfect.',
    skill: 'grammar',
    difficulty: 3,
    acceptedAnswers: ['Ik zou het gisteren hebben gedaan.', 'Ik zou het hebben gedaan.'],
  },
    {
    id: 'b2-06-ex-08',
    moduleId: 'b2-06',
    lessonId: 'b2-06-l2',
    type: 'reading-comp',
    prompt: 'Focus?',
    explanation: 'Topic in passage.',
    skill: 'reading',
    difficulty: 3,
    passage: 'In dit B2-onderdeel oefenen we future scenarios. Let op structuur en nuance.',
    options: ['future scenarios', 'spelling only', 'numbers', 'greetings'],
    acceptedAnswers: ['future scenarios'],
  },
    {
    id: 'b2-06-ex-09',
    moduleId: 'b2-06',
    lessonId: 'b2-06-l2',
    type: 'matching',
    prompt: 'Match',
    explanation: 'B2 keywords.',
    skill: 'vocabulary',
    difficulty: 2,
    acceptedAnswers: ['beleid=policy', 'bewijs=evidence', 'ambitie=ambition'],
    pairs: [{ left: 'beleid', right: 'policy' }, { left: 'bewijs', right: 'evidence' }, { left: 'ambitie', right: 'ambition' }],
  },
    {
    id: 'b2-06-ex-10',
    moduleId: 'b2-06',
    lessonId: 'b2-06-l2',
    type: 'guided-writing',
    prompt: 'Write a short B2 paragraph about future scenarios.',
    explanation: 'Self-assess.',
    skill: 'writing',
    difficulty: 3,
    modelAnswer: 'Wat future scenarios betreft, vind ik dat nuance en bewijs essentieel zijn. Bovendien helpt reflectie om betere keuzes te maken.',
    checklist: ['On topic', 'Uses at least one advanced connector', 'Clear conclusion'],
  }
];

const checkpoint: Exercise[] = [
    {
    id: 'b2-06-ex-11',
    moduleId: 'b2-06',
    type: 'multiple-choice',
    prompt: 'B2 writing should…',
    explanation: 'Argument quality.',
    skill: 'writing',
    difficulty: 2,
    options: ['support claims with reasons', 'only list words', 'avoid connectors', 'use only A1 phrases'],
    acceptedAnswers: ['support claims with reasons'],
  },
    {
    id: 'b2-06-ex-12',
    moduleId: 'b2-06',
    type: 'fill-blank',
    prompt: '_____ de bronnen betrouwbaar zijn, kun je citaten gebruiken.',
    explanation: 'Condition.',
    skill: 'grammar',
    difficulty: 2,
    acceptedAnswers: ['Mits', 'Als'],
  },
    {
    id: 'b2-06-ex-13',
    moduleId: 'b2-06',
    type: 'listening',
    prompt: 'Connector?',
    explanation: 'Moreover.',
    skill: 'listening',
    difficulty: 2,
    audioText: 'Bovendien is het goedkoper',
    options: ['Bovendien', 'Misschien', 'Hallo', 'Doei'],
    acceptedAnswers: ['Bovendien'],
  },
    {
    id: 'b2-06-ex-14',
    moduleId: 'b2-06',
    type: 'reading-comp',
    prompt: 'Tone?',
    explanation: 'Critical reading.',
    skill: 'reading',
    difficulty: 3,
    passage: 'Het artikel klinkt stellig, maar het bewijs is dun. Een kritische lezer vraagt om bronnen.',
    options: ['critical', 'celebratory', 'silent', 'childish'],
    acceptedAnswers: ['critical'],
  },
    {
    id: 'b2-06-ex-15',
    moduleId: 'b2-06',
    type: 'guided-writing',
    prompt: 'Respond to a short prompt on future scenarios in 5 sentences.',
    explanation: 'Self-assess.',
    skill: 'writing',
    difficulty: 3,
    modelAnswer: 'Mijn standpunt over future scenarios is genuanceerd. Enerzijds zie ik voordelen. Anderzijds zijn er risico\'s. Daarom stel ik een stapsgewijze aanpak voor.',
    checklist: ['Standpunt', 'Two sides or concession', 'Conclusion'],
  }
];

export const moduleB206 = createModule(
  {
    id: 'b2-06',
    level: 'b2',
    title: 'Study, society, and future scenarios',
    titleNl: 'Studie, samenleving, toekomst',
    topic: 'future-society',
    grammarFocus: ['Scenario language', 'Academic phrases', 'Advanced connectors'],
    vocabularyFocus: ['onderzoeksvraag', 'beleid', 'vooruitzicht'],
    skills: ['writing', 'reading', 'speaking', 'vocabulary'],
    description: 'Discuss study skills, societal issues, and likely future scenarios.',
    order: 30,
  },
  [
    {
      id: 'b2-06-l1',
      title: 'Academic moves',
      objective: 'Formulate a research question and paraphrase.',
      steps: [
        {
          type: 'explanation',
          title: 'Study language',
          body: 'Use onderzoeksvraag, samenvatten, parafraseren, and bronvermelding. Reflect on studybelasting without only complaining—propose strategies.',
        },
        {
          type: 'examples',
          title: 'In context',
          items: [
            { nl: 'Mijn onderzoeksvraag gaat over digitaal leren.', en: 'My research question is about digital learning.' },
            { nl: 'Vergeet de bronvermelding niet.', en: 'Do not forget the citation.' }
          ],
        },
        {
          type: 'vocabulary',
          title: 'Key words',
          vocabularyIds: ['vocab-b2-455', 'vocab-b2-456', 'vocab-b2-457', 'vocab-b2-458', 'vocab-b2-459', 'vocab-b2-477'],
        },
        {
          type: 'exercise',
          exerciseIds: ['b2-06-ex-01', 'b2-06-ex-02', 'b2-06-ex-03', 'b2-06-ex-04', 'b2-06-ex-05'],
        },
        {
          type: 'summary',
          title: 'Quick recap',
          bullets: ['Ask a clear research question', 'Cite sources'],
        },
      ],
    },
    {
      id: 'b2-06-l2',
      title: 'Society and scenarios',
      objective: 'Discuss policy and probable futures.',
      steps: [
        {
          type: 'explanation',
          title: 'Likely, unlikely, ambitious',
          body: 'Combine maatschappelijk topics (duurzaamheid, ongelijkheid, participatie) with scenario language: waarschijnlijk, onwaarschijnlijk, vooruitzicht, ambitie.',
        },
        {
          type: 'examples',
          title: 'In context',
          items: [
            { nl: 'In dit scenario groeit burgerparticipatie.', en: 'In this scenario citizen participation grows.' },
            { nl: 'De vooruitzichten voor duurzaam beleid zijn gemengd.', en: 'Prospects for sustainable policy are mixed.' }
          ],
        },
        {
          type: 'vocabulary',
          title: 'Key words',
          vocabularyIds: ['vocab-b2-460', 'vocab-b2-461', 'vocab-b2-462', 'vocab-b2-463', 'vocab-b2-465', 'vocab-b2-467'],
        },
        {
          type: 'exercise',
          exerciseIds: ['b2-06-ex-06', 'b2-06-ex-07', 'b2-06-ex-08', 'b2-06-ex-09', 'b2-06-ex-10'],
        },
        {
          type: 'summary',
          title: 'Quick recap',
          bullets: ['Link policy to consequences', 'Mark probability clearly'],
        },
      ],
    }
  ],
  lessonExercises,
  checkpoint,
);

export const moduleB206Exercises = lessonExercises;
