import { createModule } from './moduleFactory';
import type { Exercise } from '../types';

const lessonExercises: Exercise[] = [
    {
    id: 'b2-04-ex-01',
    moduleId: 'b2-04',
    lessonId: 'b2-04-l1',
    type: 'multiple-choice',
    prompt: 'Core theme of this module?',
    explanation: 'Theme recognition.',
    skill: 'vocabulary',
    difficulty: 2,
    options: ['culture', 'Only alphabet', 'Only numbers', 'Cooking recipes'],
    acceptedAnswers: ['culture'],
  },
    {
    id: 'b2-04-ex-02',
    moduleId: 'b2-04',
    lessonId: 'b2-04-l1',
    type: 'fill-blank',
    prompt: '_____ ik meer tijd had, zou ik helpen.',
    explanation: 'Conditional als-clause.',
    skill: 'grammar',
    difficulty: 2,
    acceptedAnswers: ['Als'],
  },
    {
    id: 'b2-04-ex-03',
    moduleId: 'b2-04',
    lessonId: 'b2-04-l1',
    type: 'sentence-order',
    prompt: 'Order',
    explanation: 'Conditional zou.',
    skill: 'grammar',
    difficulty: 2,
    acceptedAnswers: ['Ik zou het anders aanpakken.'],
    orderItems: ['zou', 'Ik', 'het', 'anders', 'aanpakken', '.'],
  },
    {
    id: 'b2-04-ex-04',
    moduleId: 'b2-04',
    lessonId: 'b2-04-l1',
    type: 'listening',
    prompt: 'Pick the word',
    explanation: 'Listening recognition.',
    skill: 'listening',
    difficulty: 2,
    audioText: 'recensie',
    options: ['recensie', 'fiets', 'soep', 'stoel'],
    acceptedAnswers: ['recensie'],
  },
    {
    id: 'b2-04-ex-05',
    moduleId: 'b2-04',
    lessonId: 'b2-04-l1',
    type: 'translation-en-nl',
    prompt: 'Translate: De tentoonstelling is indrukwekkend',
    explanation: 'Target phrase.',
    skill: 'writing',
    difficulty: 3,
    acceptedAnswers: ['De tentoonstelling is indrukwekkend'],
  },
    {
    id: 'b2-04-ex-06',
    moduleId: 'b2-04',
    lessonId: 'b2-04-l2',
    type: 'fill-blank',
    prompt: '_____ de tekst kritisch.',
    explanation: 'Imperative / instruction.',
    skill: 'grammar',
    difficulty: 2,
    acceptedAnswers: ['Lees', 'lees'],
  },
    {
    id: 'b2-04-ex-07',
    moduleId: 'b2-04',
    lessonId: 'b2-04-l2',
    type: 'error-correction',
    prompt: 'Fix: Ik zou hebben het gedaan gisteren.',
    explanation: 'Participle placement in conditional perfect.',
    skill: 'grammar',
    difficulty: 3,
    acceptedAnswers: ['Ik zou het gisteren hebben gedaan.', 'Ik zou het hebben gedaan.'],
  },
    {
    id: 'b2-04-ex-08',
    moduleId: 'b2-04',
    lessonId: 'b2-04-l2',
    type: 'reading-comp',
    prompt: 'Focus?',
    explanation: 'Topic in passage.',
    skill: 'reading',
    difficulty: 3,
    passage: 'In dit B2-onderdeel oefenen we culture. Let op structuur en nuance.',
    options: ['culture', 'spelling only', 'numbers', 'greetings'],
    acceptedAnswers: ['culture'],
  },
    {
    id: 'b2-04-ex-09',
    moduleId: 'b2-04',
    lessonId: 'b2-04-l2',
    type: 'matching',
    prompt: 'Match',
    explanation: 'B2 keywords.',
    skill: 'vocabulary',
    difficulty: 2,
    acceptedAnswers: ['beleid=policy', 'bewijs=evidence', 'ambitie=ambition'],
    pairs: [{ left: 'beleid', right: 'policy' }, { left: 'bewijs', right: 'evidence' }, { left: 'ambitie', right: 'ambition' }],
  },
    {
    id: 'b2-04-ex-10',
    moduleId: 'b2-04',
    lessonId: 'b2-04-l2',
    type: 'guided-writing',
    prompt: 'Write a short B2 paragraph about culture.',
    explanation: 'Self-assess.',
    skill: 'writing',
    difficulty: 3,
    modelAnswer: 'Wat culture betreft, vind ik dat nuance en bewijs essentieel zijn. Bovendien helpt reflectie om betere keuzes te maken.',
    checklist: ['On topic', 'Uses at least one advanced connector', 'Clear conclusion'],
  }
];

const checkpoint: Exercise[] = [
    {
    id: 'b2-04-ex-11',
    moduleId: 'b2-04',
    type: 'multiple-choice',
    prompt: 'B2 writing should…',
    explanation: 'Argument quality.',
    skill: 'writing',
    difficulty: 2,
    options: ['support claims with reasons', 'only list words', 'avoid connectors', 'use only A1 phrases'],
    acceptedAnswers: ['support claims with reasons'],
  },
    {
    id: 'b2-04-ex-12',
    moduleId: 'b2-04',
    type: 'fill-blank',
    prompt: '_____ de bronnen betrouwbaar zijn, kun je citaten gebruiken.',
    explanation: 'Condition.',
    skill: 'grammar',
    difficulty: 2,
    acceptedAnswers: ['Mits', 'Als'],
  },
    {
    id: 'b2-04-ex-13',
    moduleId: 'b2-04',
    type: 'listening',
    prompt: 'Connector?',
    explanation: 'Moreover.',
    skill: 'listening',
    difficulty: 2,
    audioText: 'Bovendien is het goedkoper',
    options: ['Bovendien', 'Misschien', 'Hallo', 'Doei'],
    acceptedAnswers: ['Bovendien'],
  },
    {
    id: 'b2-04-ex-14',
    moduleId: 'b2-04',
    type: 'reading-comp',
    prompt: 'Tone?',
    explanation: 'Critical reading.',
    skill: 'reading',
    difficulty: 3,
    passage: 'Het artikel klinkt stellig, maar het bewijs is dun. Een kritische lezer vraagt om bronnen.',
    options: ['critical', 'celebratory', 'silent', 'childish'],
    acceptedAnswers: ['critical'],
  },
    {
    id: 'b2-04-ex-15',
    moduleId: 'b2-04',
    type: 'guided-writing',
    prompt: 'Respond to a short prompt on culture in 5 sentences.',
    explanation: 'Self-assess.',
    skill: 'writing',
    difficulty: 3,
    modelAnswer: 'Mijn standpunt over culture is genuanceerd. Enerzijds zie ik voordelen. Anderzijds zijn er risico\'s. Daarom stel ik een stapsgewijze aanpak voor.',
    checklist: ['Standpunt', 'Two sides or concession', 'Conclusion'],
  }
];

export const moduleB204 = createModule(
  {
    id: 'b2-04',
    level: 'b2',
    title: 'Culture and interpretation',
    titleNl: 'Cultuur en interpretatie',
    topic: 'culture',
    grammarFocus: ['Relative clauses for detail', 'Abstract nouns', 'Opinion frames'],
    vocabularyFocus: ['interpretatie', 'tentoonstelling', 'recensie'],
    skills: ['reading', 'writing', 'speaking', 'vocabulary'],
    description: 'Discuss exhibitions, reviews, and abstract cultural ideas.',
    order: 28,
  },
  [
    {
      id: 'b2-04-l1',
      title: 'Talking about art and reviews',
      objective: 'Describe and evaluate a cultural experience.',
      steps: [
        {
          type: 'explanation',
          title: 'From concrete to abstract',
          body: 'Move from what you saw to interpretatie. A recensie balances description and judgement. Relative clauses add precision: het werk dat…',
        },
        {
          type: 'examples',
          title: 'In context',
          items: [
            { nl: 'De tentoonstelling die ik bezocht, was indrukwekkend.', en: 'The exhibition I visited was impressive.' },
            { nl: 'Mijn interpretatie verschilt van de recensie.', en: 'My interpretation differs from the review.' }
          ],
        },
        {
          type: 'vocabulary',
          title: 'Key words',
          vocabularyIds: ['vocab-b2-445', 'vocab-b2-446', 'vocab-b2-447', 'vocab-b2-448', 'vocab-b2-449', 'vocab-b2-450'],
        },
        {
          type: 'exercise',
          exerciseIds: ['b2-04-ex-01', 'b2-04-ex-02', 'b2-04-ex-03', 'b2-04-ex-04', 'b2-04-ex-05'],
        },
        {
          type: 'summary',
          title: 'Quick recap',
          bullets: ['Describe then interpret', 'Use relative clauses for detail'],
        },
      ],
    },
    {
      id: 'b2-04-l2',
      title: 'Writing a short review',
      objective: 'Produce a structured mini-recensie.',
      steps: [
        {
          type: 'explanation',
          title: 'Structure helps',
          body: 'Context → description → interpretation → recommendation. Keep claims fair and specific.',
        },
        {
          type: 'examples',
          title: 'In context',
          items: [
            { nl: 'Ik raad de tentoonstelling aan vanwege de heldere opbouw.', en: 'I recommend the exhibition because of its clear structure.' },
            { nl: 'Het thema blijft soms te abstract.', en: 'The theme sometimes stays too abstract.' }
          ],
        },
        {
          type: 'vocabulary',
          title: 'Key words',
          vocabularyIds: ['vocab-b2-448', 'vocab-b2-445', 'vocab-b2-446', 'vocab-b2-450', 'vocab-b2-454', 'vocab-b2-472'],
        },
        {
          type: 'exercise',
          exerciseIds: ['b2-04-ex-06', 'b2-04-ex-07', 'b2-04-ex-08', 'b2-04-ex-09', 'b2-04-ex-10'],
        },
        {
          type: 'summary',
          title: 'Quick recap',
          bullets: ['Recommend with reasons', 'Mention one limitation'],
        },
      ],
    }
  ],
  lessonExercises,
  checkpoint,
);

export const moduleB204Exercises = lessonExercises;
