import { createModule } from './moduleFactory';
import type { Exercise } from '../types';

const lessonExercises: Exercise[] = [
    {
    id: 'b2-02-ex-01',
    moduleId: 'b2-02',
    lessonId: 'b2-02-l1',
    type: 'multiple-choice',
    prompt: 'Core theme of this module?',
    explanation: 'Theme recognition.',
    skill: 'vocabulary',
    difficulty: 2,
    options: ['negotiation', 'Only alphabet', 'Only numbers', 'Cooking recipes'],
    acceptedAnswers: ['negotiation'],
  },
    {
    id: 'b2-02-ex-02',
    moduleId: 'b2-02',
    lessonId: 'b2-02-l1',
    type: 'fill-blank',
    prompt: '_____ ik meer tijd had, zou ik helpen.',
    explanation: 'Conditional als-clause.',
    skill: 'grammar',
    difficulty: 2,
    acceptedAnswers: ['Als'],
  },
    {
    id: 'b2-02-ex-03',
    moduleId: 'b2-02',
    lessonId: 'b2-02-l1',
    type: 'sentence-order',
    prompt: 'Order',
    explanation: 'Conditional zou.',
    skill: 'grammar',
    difficulty: 2,
    acceptedAnswers: ['Ik zou het anders aanpakken.'],
    orderItems: ['zou', 'Ik', 'het', 'anders', 'aanpakken', '.'],
  },
    {
    id: 'b2-02-ex-04',
    moduleId: 'b2-02',
    lessonId: 'b2-02-l1',
    type: 'listening',
    prompt: 'Pick the word',
    explanation: 'Listening recognition.',
    skill: 'listening',
    difficulty: 2,
    audioText: 'compromis',
    options: ['compromis', 'fiets', 'soep', 'stoel'],
    acceptedAnswers: ['compromis'],
  },
    {
    id: 'b2-02-ex-05',
    moduleId: 'b2-02',
    lessonId: 'b2-02-l1',
    type: 'translation-en-nl',
    prompt: 'Translate: Ik wil onderhandelen',
    explanation: 'Target phrase.',
    skill: 'writing',
    difficulty: 3,
    acceptedAnswers: ['Ik wil onderhandelen'],
  },
    {
    id: 'b2-02-ex-06',
    moduleId: 'b2-02',
    lessonId: 'b2-02-l2',
    type: 'fill-blank',
    prompt: '_____ de tekst kritisch.',
    explanation: 'Imperative / instruction.',
    skill: 'grammar',
    difficulty: 2,
    acceptedAnswers: ['Lees', 'lees'],
  },
    {
    id: 'b2-02-ex-07',
    moduleId: 'b2-02',
    lessonId: 'b2-02-l2',
    type: 'error-correction',
    prompt: 'Fix: Ik zou hebben het gedaan gisteren.',
    explanation: 'Participle placement in conditional perfect.',
    skill: 'grammar',
    difficulty: 3,
    acceptedAnswers: ['Ik zou het gisteren hebben gedaan.', 'Ik zou het hebben gedaan.'],
  },
    {
    id: 'b2-02-ex-08',
    moduleId: 'b2-02',
    lessonId: 'b2-02-l2',
    type: 'reading-comp',
    prompt: 'Focus?',
    explanation: 'Topic in passage.',
    skill: 'reading',
    difficulty: 3,
    passage: 'In dit B2-onderdeel oefenen we negotiation. Let op structuur en nuance.',
    options: ['negotiation', 'spelling only', 'numbers', 'greetings'],
    acceptedAnswers: ['negotiation'],
  },
    {
    id: 'b2-02-ex-09',
    moduleId: 'b2-02',
    lessonId: 'b2-02-l2',
    type: 'matching',
    prompt: 'Match',
    explanation: 'B2 keywords.',
    skill: 'vocabulary',
    difficulty: 2,
    acceptedAnswers: ['beleid=policy', 'bewijs=evidence', 'ambitie=ambition'],
    pairs: [{ left: 'beleid', right: 'policy' }, { left: 'bewijs', right: 'evidence' }, { left: 'ambitie', right: 'ambition' }],
  },
    {
    id: 'b2-02-ex-10',
    moduleId: 'b2-02',
    lessonId: 'b2-02-l2',
    type: 'guided-writing',
    prompt: 'Write a short B2 paragraph about negotiation.',
    explanation: 'Self-assess.',
    skill: 'writing',
    difficulty: 3,
    modelAnswer: 'Wat negotiation betreft, vind ik dat nuance en bewijs essentieel zijn. Bovendien helpt reflectie om betere keuzes te maken.',
    checklist: ['On topic', 'Uses at least one advanced connector', 'Clear conclusion'],
  }
];

const checkpoint: Exercise[] = [
    {
    id: 'b2-02-ex-11',
    moduleId: 'b2-02',
    type: 'multiple-choice',
    prompt: 'B2 writing should…',
    explanation: 'Argument quality.',
    skill: 'writing',
    difficulty: 2,
    options: ['support claims with reasons', 'only list words', 'avoid connectors', 'use only A1 phrases'],
    acceptedAnswers: ['support claims with reasons'],
  },
    {
    id: 'b2-02-ex-12',
    moduleId: 'b2-02',
    type: 'fill-blank',
    prompt: '_____ de bronnen betrouwbaar zijn, kun je citaten gebruiken.',
    explanation: 'Condition.',
    skill: 'grammar',
    difficulty: 2,
    acceptedAnswers: ['Mits', 'Als'],
  },
    {
    id: 'b2-02-ex-13',
    moduleId: 'b2-02',
    type: 'listening',
    prompt: 'Connector?',
    explanation: 'Moreover.',
    skill: 'listening',
    difficulty: 2,
    audioText: 'Bovendien is het goedkoper',
    options: ['Bovendien', 'Misschien', 'Hallo', 'Doei'],
    acceptedAnswers: ['Bovendien'],
  },
    {
    id: 'b2-02-ex-14',
    moduleId: 'b2-02',
    type: 'reading-comp',
    prompt: 'Tone?',
    explanation: 'Critical reading.',
    skill: 'reading',
    difficulty: 3,
    passage: 'Het artikel klinkt stellig, maar het bewijs is dun. Een kritische lezer vraagt om bronnen.',
    options: ['critical', 'celebratory', 'silent', 'childish'],
    acceptedAnswers: ['critical'],
  },
    {
    id: 'b2-02-ex-15',
    moduleId: 'b2-02',
    type: 'guided-writing',
    prompt: 'Respond to a short prompt on negotiation in 5 sentences.',
    explanation: 'Self-assess.',
    skill: 'writing',
    difficulty: 3,
    modelAnswer: 'Mijn standpunt over negotiation is genuanceerd. Enerzijds zie ik voordelen. Anderzijds zijn er risico\'s. Daarom stel ik een stapsgewijze aanpak voor.',
    checklist: ['Standpunt', 'Two sides or concession', 'Conclusion'],
  }
];

export const moduleB202 = createModule(
  {
    id: 'b2-02',
    level: 'b2',
    title: 'Workplace negotiation',
    titleNl: 'Onderhandelen op het werk',
    topic: 'negotiation',
    grammarFocus: ['Polite conditionals', 'Passive in minutes', 'Formal register'],
    vocabularyFocus: ['onderhandelen', 'compromis', 'voorwaarde'],
    skills: ['speaking', 'writing', 'listening', 'grammar'],
    description: 'Negotiate deadlines, conditions, and compromises in professional Dutch.',
    order: 26,
  },
  [
    {
      id: 'b2-02-l1',
      title: 'Setting conditions politely',
      objective: 'Propose conditions with zou and mits.',
      steps: [
        {
          type: 'explanation',
          title: 'Soft power language',
          body: 'In meetings, soften proposals: Zou het mogelijk zijn…? We kunnen akkoord gaan, mits… Passives appear in minutes: Er werd besloten dat…',
        },
        {
          type: 'examples',
          title: 'In context',
          items: [
            { nl: 'Zou het lukken om de deadline te verschuiven?', en: 'Would it be possible to move the deadline?' },
            { nl: 'We gaan akkoord, mits de voorwaarden duidelijk zijn.', en: 'We agree, provided the conditions are clear.' }
          ],
        },
        {
          type: 'vocabulary',
          title: 'Key words',
          vocabularyIds: ['vocab-b2-434', 'vocab-b2-435', 'vocab-b2-436', 'vocab-b2-437', 'vocab-b2-438', 'vocab-b2-439'],
        },
        {
          type: 'exercise',
          exerciseIds: ['b2-02-ex-01', 'b2-02-ex-02', 'b2-02-ex-03', 'b2-02-ex-04', 'b2-02-ex-05'],
        },
        {
          type: 'summary',
          title: 'Quick recap',
          bullets: ['Use zou for polite proposals', 'Record decisions with clear conditions'],
        },
      ],
    },
    {
      id: 'b2-02-l2',
      title: 'Finding a compromise',
      objective: 'Offer and evaluate a compromise.',
      steps: [
        {
          type: 'explanation',
          title: 'Win–win phrasing',
          body: 'Name priorities, offer a compromis, and confirm next steps. Stakeholders expect clarity more than dramatic rhetoric.',
        },
        {
          type: 'examples',
          title: 'In context',
          items: [
            { nl: 'Laten we een compromis zoeken over de planning.', en: 'Let us look for a compromise on the schedule.' },
            { nl: 'De prioriteit is kwaliteit, niet snelheid.', en: 'The priority is quality, not speed.' }
          ],
        },
        {
          type: 'vocabulary',
          title: 'Key words',
          vocabularyIds: ['vocab-b2-478', 'vocab-b2-479', 'vocab-b2-480', 'vocab-b2-437', 'vocab-b2-436', 'vocab-b2-435'],
        },
        {
          type: 'exercise',
          exerciseIds: ['b2-02-ex-06', 'b2-02-ex-07', 'b2-02-ex-08', 'b2-02-ex-09', 'b2-02-ex-10'],
        },
        {
          type: 'summary',
          title: 'Quick recap',
          bullets: ['State priorities', 'Confirm the deal in writing'],
        },
      ],
    }
  ],
  lessonExercises,
  checkpoint,
);

export const moduleB202Exercises = lessonExercises;
