import { createModule } from './moduleFactory';
import type { Exercise } from '../types';

const lessonExercises: Exercise[] = [
    {
    id: 'b2-01-ex-01',
    moduleId: 'b2-01',
    lessonId: 'b2-01-l1',
    type: 'multiple-choice',
    prompt: 'Hoewel introduces…',
    explanation: 'Hoewel = although.',
    skill: 'grammar',
    difficulty: 2,
    options: ['a concessive clause', 'only past tense', 'a question tag', 'an imperative'],
    acceptedAnswers: ['a concessive clause'],
  },
    {
    id: 'b2-01-ex-02',
    moduleId: 'b2-01',
    lessonId: 'b2-01-l1',
    type: 'fill-blank',
    prompt: '_____ het laat is, werk ik door.',
    explanation: 'Hoewel + concession.',
    skill: 'grammar',
    difficulty: 2,
    acceptedAnswers: ['Hoewel'],
  },
    {
    id: 'b2-01-ex-03',
    moduleId: 'b2-01',
    lessonId: 'b2-01-l1',
    type: 'sentence-order',
    prompt: 'Order',
    explanation: 'Verb final in hoewel-clause.',
    skill: 'grammar',
    difficulty: 2,
    acceptedAnswers: ['Hoewel het duur is, steun ik het.'],
    orderItems: ['is', 'duur', 'het', 'Hoewel', ',', 'steun', 'ik', 'het', '.'],
  },
    {
    id: 'b2-01-ex-04',
    moduleId: 'b2-01',
    lessonId: 'b2-01-l1',
    type: 'multiple-choice',
    prompt: 'Enerzijds pairs best with…',
    explanation: 'Two-sided framing.',
    skill: 'vocabulary',
    difficulty: 2,
    options: ['anderzijds', 'daarom alleen', 'gisteren', 'alsjeblieft'],
    acceptedAnswers: ['anderzijds'],
  },
    {
    id: 'b2-01-ex-05',
    moduleId: 'b2-01',
    lessonId: 'b2-01-l1',
    type: 'listening',
    prompt: 'Which connector?',
    explanation: 'Nevertheless.',
    skill: 'listening',
    difficulty: 2,
    audioText: 'Desalniettemin ga ik door',
    options: ['Desalniettemin', 'Misschien', 'Hallo', 'Graag'],
    acceptedAnswers: ['Desalniettemin'],
  },
    {
    id: 'b2-01-ex-06',
    moduleId: 'b2-01',
    lessonId: 'b2-01-l2',
    type: 'fill-blank',
    prompt: 'Wat is jouw _____ over dit plan?',
    explanation: 'Standpunt = viewpoint.',
    skill: 'grammar',
    difficulty: 2,
    acceptedAnswers: ['standpunt'],
  },
    {
    id: 'b2-01-ex-07',
    moduleId: 'b2-01',
    lessonId: 'b2-01-l2',
    type: 'translation-en-nl',
    prompt: 'Translate: I want to nuance my opinion.',
    explanation: 'Nuanceren.',
    skill: 'writing',
    difficulty: 3,
    acceptedAnswers: ['Ik wil mijn mening nuanceren.'],
  },
    {
    id: 'b2-01-ex-08',
    moduleId: 'b2-01',
    lessonId: 'b2-01-l2',
    type: 'error-correction',
    prompt: 'Fix: Hoewel het is duur, koop ik het.',
    explanation: 'Verb goes to the end in the subordinate clause.',
    skill: 'grammar',
    difficulty: 3,
    acceptedAnswers: ['Hoewel het duur is, koop ik het.'],
  },
    {
    id: 'b2-01-ex-09',
    moduleId: 'b2-01',
    lessonId: 'b2-01-l2',
    type: 'reading-comp',
    prompt: 'What is the writer’s move?',
    explanation: 'Classic debate move.',
    skill: 'reading',
    difficulty: 3,
    passage: 'Ik erken het tegenargument over kosten. Desalniettemin zie ik langetermijnwinst.',
    options: ['acknowledges then counters', 'gives up', 'asks a price', 'tells a joke'],
    acceptedAnswers: ['acknowledges then counters'],
  },
    {
    id: 'b2-01-ex-10',
    moduleId: 'b2-01',
    lessonId: 'b2-01-l2',
    type: 'guided-writing',
    prompt: 'Write 4–5 sentences: standpunt, tegenargument, response, conclusion.',
    explanation: 'Self-assess.',
    skill: 'writing',
    difficulty: 3,
    modelAnswer: 'Mijn standpunt is dat openbaar vervoer voorrang moet krijgen. Een tegenargument is de korte termijnkosten. Desalniettemin dalen de files en de uitstoot. Daarom steun ik de investering.',
    checklist: ['States a standpunt', 'Names a tegenargument', 'Uses a B2 connector'],
  }
];

const checkpoint: Exercise[] = [
    {
    id: 'b2-01-ex-11',
    moduleId: 'b2-01',
    type: 'multiple-choice',
    prompt: 'Tenzij means…',
    explanation: 'Condition of exclusion.',
    skill: 'vocabulary',
    difficulty: 2,
    options: ['unless', 'because', 'before', 'during'],
    acceptedAnswers: ['unless'],
  },
    {
    id: 'b2-01-ex-12',
    moduleId: 'b2-01',
    type: 'fill-blank',
    prompt: 'Je mag lenen, _____ je het terugbetaalt.',
    explanation: 'Mits = provided that.',
    skill: 'grammar',
    difficulty: 2,
    acceptedAnswers: ['mits'],
  },
    {
    id: 'b2-01-ex-13',
    moduleId: 'b2-01',
    type: 'matching',
    prompt: 'Match connectors',
    explanation: 'High-frequency B2 connectors.',
    skill: 'vocabulary',
    difficulty: 2,
    acceptedAnswers: ['hoewel=although', 'desalniettemin=nevertheless', 'bovendien=moreover'],
    pairs: [{ left: 'hoewel', right: 'although' }, { left: 'desalniettemin', right: 'nevertheless' }, { left: 'bovendien', right: 'moreover' }],
  },
    {
    id: 'b2-01-ex-14',
    moduleId: 'b2-01',
    type: 'reading-comp',
    prompt: 'Main claim?',
    explanation: 'Uiteindelijk introduces the conclusion.',
    skill: 'reading',
    difficulty: 3,
    passage: 'Enerzijds is digitaal werken flexibel. Anderzijds vraagt het discipline. Uiteindelijk hangt succes af van duidelijke afspraken.',
    options: ['success depends on clear agreements', 'digital work always fails', 'discipline is unimportant', 'flexibility is banned'],
    acceptedAnswers: ['success depends on clear agreements'],
  },
    {
    id: 'b2-01-ex-15',
    moduleId: 'b2-01',
    type: 'guided-writing',
    prompt: 'Argue for or against longer library opening hours (B2 paragraph).',
    explanation: 'Self-assess.',
    skill: 'writing',
    difficulty: 3,
    modelAnswer: 'Hoewel langere openingstijden geld kosten, verbeteren ze studiekansen. Bovendien gebruiken veel studenten de avonduren. Daarom ben ik voor een proefperiode.',
    checklist: ['Uses a concessive or two-sided connector', 'Gives a reason', 'Ends with a clear position'],
  }
];

export const moduleB201 = createModule(
  {
    id: 'b2-01',
    level: 'b2',
    title: 'Nuanced opinions and debate',
    titleNl: 'Nuances en debat',
    topic: 'argument',
    grammarFocus: ['hoewel/mits/tenzij', 'enerzijds/anderzijds', 'Nominal style'],
    vocabularyFocus: ['standpunt', 'tegenargument', 'nuance'],
    skills: ['writing', 'speaking', 'grammar', 'reading'],
    description: 'Argue with nuance using advanced connectors and balanced structure.',
    order: 25,
  },
  [
    {
      id: 'b2-01-l1',
      title: 'Connectors for balanced views',
      objective: 'Use hoewel, mits, tenzij, enerzijds/anderzijds.',
      steps: [
        {
          type: 'explanation',
          title: 'Beyond omdat and maar',
          body: 'At B2 you weigh ideas. Hoewel opens a concessive clause (verb final). Mits and tenzij set conditions. Enerzijds… anderzijds… frames two sides without sounding childish.',
        },
        {
          type: 'examples',
          title: 'In context',
          items: [
            { nl: 'Hoewel het plan duur is, steun ik het.', en: 'Although the plan is expensive, I support it.' },
            { nl: 'Enerzijds besparen we, anderzijds investeren we.', en: 'On the one hand we save, on the other we invest.' }
          ],
        },
        {
          type: 'vocabulary',
          title: 'Key words',
          vocabularyIds: ['vocab-b2-421', 'vocab-b2-422', 'vocab-b2-426', 'vocab-b2-427', 'vocab-b2-430', 'vocab-b2-431'],
        },
        {
          type: 'exercise',
          exerciseIds: ['b2-01-ex-01', 'b2-01-ex-02', 'b2-01-ex-03', 'b2-01-ex-04', 'b2-01-ex-05'],
        },
        {
          type: 'summary',
          title: 'Quick recap',
          bullets: ['Hoewel + verb at end', 'Use enerzijds/anderzijds for balance'],
        },
      ],
    },
    {
      id: 'b2-01-l2',
      title: 'Building a counter-argument',
      objective: 'State a position and answer a counter-argument.',
      steps: [
        {
          type: 'explanation',
          title: 'Standpunt + tegenargument',
          body: 'State your standpunt clearly, acknowledge a tegenargument, then respond with bewijs or a nuance. Avoid absolute claims when evidence is thin.',
        },
        {
          type: 'examples',
          title: 'In context',
          items: [
            { nl: 'Mijn standpunt is dat thuiswerken productiever kan zijn.', en: 'My position is that working from home can be more productive.' },
            { nl: 'Een tegenargument is minder teamcontact; desalniettemin helpt digitaal overleg.', en: 'A counter-argument is less team contact; nevertheless digital meetings help.' }
          ],
        },
        {
          type: 'vocabulary',
          title: 'Key words',
          vocabularyIds: ['vocab-b2-423', 'vocab-b2-424', 'vocab-b2-474', 'vocab-b2-475', 'vocab-b2-476', 'vocab-b2-425'],
        },
        {
          type: 'exercise',
          exerciseIds: ['b2-01-ex-06', 'b2-01-ex-07', 'b2-01-ex-08', 'b2-01-ex-09', 'b2-01-ex-10'],
        },
        {
          type: 'summary',
          title: 'Quick recap',
          bullets: ['Acknowledge then respond', 'Prefer evidence over slogans'],
        },
      ],
    }
  ],
  lessonExercises,
  checkpoint,
);

export const moduleB201Exercises = lessonExercises;
