import { createModule } from './moduleFactory';
import type { Exercise } from '../types';

const lessonExercises: Exercise[] = [
    {
    id: 'b2-03-ex-01',
    moduleId: 'b2-03',
    lessonId: 'b2-03-l1',
    type: 'multiple-choice',
    prompt: 'Core theme of this module?',
    explanation: 'Theme recognition.',
    skill: 'vocabulary',
    difficulty: 2,
    options: ['media literacy', 'Only alphabet', 'Only numbers', 'Cooking recipes'],
    acceptedAnswers: ['media literacy'],
  },
    {
    id: 'b2-03-ex-02',
    moduleId: 'b2-03',
    lessonId: 'b2-03-l1',
    type: 'fill-blank',
    prompt: '_____ ik meer tijd had, zou ik helpen.',
    explanation: 'Conditional als-clause.',
    skill: 'grammar',
    difficulty: 2,
    acceptedAnswers: ['Als'],
  },
    {
    id: 'b2-03-ex-03',
    moduleId: 'b2-03',
    lessonId: 'b2-03-l1',
    type: 'sentence-order',
    prompt: 'Order',
    explanation: 'Conditional zou.',
    skill: 'grammar',
    difficulty: 2,
    acceptedAnswers: ['Ik zou het anders aanpakken.'],
    orderItems: ['zou', 'Ik', 'het', 'anders', 'aanpakken', '.'],
  },
    {
    id: 'b2-03-ex-04',
    moduleId: 'b2-03',
    lessonId: 'b2-03-l1',
    type: 'listening',
    prompt: 'Pick the word',
    explanation: 'Listening recognition.',
    skill: 'listening',
    difficulty: 2,
    audioText: 'bronnen',
    options: ['bronnen', 'fiets', 'soep', 'stoel'],
    acceptedAnswers: ['bronnen'],
  },
    {
    id: 'b2-03-ex-05',
    moduleId: 'b2-03',
    lessonId: 'b2-03-l1',
    type: 'translation-en-nl',
    prompt: 'Translate: Lees kritisch',
    explanation: 'Target phrase.',
    skill: 'writing',
    difficulty: 3,
    acceptedAnswers: ['Lees kritisch'],
  },
    {
    id: 'b2-03-ex-06',
    moduleId: 'b2-03',
    lessonId: 'b2-03-l2',
    type: 'fill-blank',
    prompt: '_____ de tekst kritisch.',
    explanation: 'Imperative / instruction.',
    skill: 'grammar',
    difficulty: 2,
    acceptedAnswers: ['Lees', 'lees'],
  },
    {
    id: 'b2-03-ex-07',
    moduleId: 'b2-03',
    lessonId: 'b2-03-l2',
    type: 'error-correction',
    prompt: 'Fix: Ik zou hebben het gedaan gisteren.',
    explanation: 'Participle placement in conditional perfect.',
    skill: 'grammar',
    difficulty: 3,
    acceptedAnswers: ['Ik zou het gisteren hebben gedaan.', 'Ik zou het hebben gedaan.'],
  },
    {
    id: 'b2-03-ex-08',
    moduleId: 'b2-03',
    lessonId: 'b2-03-l2',
    type: 'reading-comp',
    prompt: 'Focus?',
    explanation: 'Topic in passage.',
    skill: 'reading',
    difficulty: 3,
    passage: 'In dit B2-onderdeel oefenen we media literacy. Let op structuur en nuance.',
    options: ['media literacy', 'spelling only', 'numbers', 'greetings'],
    acceptedAnswers: ['media literacy'],
  },
    {
    id: 'b2-03-ex-09',
    moduleId: 'b2-03',
    lessonId: 'b2-03-l2',
    type: 'matching',
    prompt: 'Match',
    explanation: 'B2 keywords.',
    skill: 'vocabulary',
    difficulty: 2,
    acceptedAnswers: ['beleid=policy', 'bewijs=evidence', 'ambitie=ambition'],
    pairs: [{ left: 'beleid', right: 'policy' }, { left: 'bewijs', right: 'evidence' }, { left: 'ambitie', right: 'ambition' }],
  },
    {
    id: 'b2-03-ex-10',
    moduleId: 'b2-03',
    lessonId: 'b2-03-l2',
    type: 'guided-writing',
    prompt: 'Write a short B2 paragraph about media literacy.',
    explanation: 'Self-assess.',
    skill: 'writing',
    difficulty: 3,
    modelAnswer: 'Wat media literacy betreft, vind ik dat nuance en bewijs essentieel zijn. Bovendien helpt reflectie om betere keuzes te maken.',
    checklist: ['On topic', 'Uses at least one advanced connector', 'Clear conclusion'],
  }
];

const checkpoint: Exercise[] = [
    {
    id: 'b2-03-ex-11',
    moduleId: 'b2-03',
    type: 'multiple-choice',
    prompt: 'B2 writing should…',
    explanation: 'Argument quality.',
    skill: 'writing',
    difficulty: 2,
    options: ['support claims with reasons', 'only list words', 'avoid connectors', 'use only A1 phrases'],
    acceptedAnswers: ['support claims with reasons'],
  },
    {
    id: 'b2-03-ex-12',
    moduleId: 'b2-03',
    type: 'fill-blank',
    prompt: '_____ de bronnen betrouwbaar zijn, kun je citaten gebruiken.',
    explanation: 'Condition.',
    skill: 'grammar',
    difficulty: 2,
    acceptedAnswers: ['Mits', 'Als'],
  },
    {
    id: 'b2-03-ex-13',
    moduleId: 'b2-03',
    type: 'listening',
    prompt: 'Connector?',
    explanation: 'Moreover.',
    skill: 'listening',
    difficulty: 2,
    audioText: 'Bovendien is het goedkoper',
    options: ['Bovendien', 'Misschien', 'Hallo', 'Doei'],
    acceptedAnswers: ['Bovendien'],
  },
    {
    id: 'b2-03-ex-14',
    moduleId: 'b2-03',
    type: 'reading-comp',
    prompt: 'Tone?',
    explanation: 'Critical reading.',
    skill: 'reading',
    difficulty: 3,
    passage: 'Het artikel klinkt stellig, maar het bewijs is dun. Een kritische lezer vraagt om bronnen.',
    options: ['critical', 'celebratory', 'silent', 'childish'],
    acceptedAnswers: ['critical'],
  },
    {
    id: 'b2-03-ex-15',
    moduleId: 'b2-03',
    type: 'guided-writing',
    prompt: 'Respond to a short prompt on media literacy in 5 sentences.',
    explanation: 'Self-assess.',
    skill: 'writing',
    difficulty: 3,
    modelAnswer: 'Mijn standpunt over media literacy is genuanceerd. Enerzijds zie ik voordelen. Anderzijds zijn er risico\'s. Daarom stel ik een stapsgewijze aanpak voor.',
    checklist: ['Standpunt', 'Two sides or concession', 'Conclusion'],
  }
];

export const moduleB203 = createModule(
  {
    id: 'b2-03',
    level: 'b2',
    title: 'Media literacy',
    titleNl: 'Kritisch met media',
    topic: 'media',
    grammarFocus: ['Reported claims', 'Hedging language', 'Complex noun phrases'],
    vocabularyFocus: ['bron', 'desinformatie', 'berichtgeving'],
    skills: ['reading', 'listening', 'writing', 'vocabulary'],
    description: 'Evaluate sources, bias, and claims in Dutch media texts.',
    order: 27,
  },
  [
    {
      id: 'b2-03-l1',
      title: 'Checking sources',
      objective: 'Ask critical questions about a news claim.',
      steps: [
        {
          type: 'explanation',
          title: 'Who says what, and based on what?',
          body: 'At B2, separate claim, bron, and bewijs. Hedging helps: het lijkt erop dat…, volgens de berichtgeving… Avoid repeating viral claims without checking.',
        },
        {
          type: 'examples',
          title: 'In context',
          items: [
            { nl: 'Volgens de berichtgeving daalt de werkloosheid.', en: 'According to the coverage, unemployment is falling.' },
            { nl: 'Controleer altijd je bronnen.', en: 'Always check your sources.' }
          ],
        },
        {
          type: 'vocabulary',
          title: 'Key words',
          vocabularyIds: ['vocab-b2-440', 'vocab-b2-441', 'vocab-b2-442', 'vocab-b2-443', 'vocab-b2-444', 'vocab-b2-476'],
        },
        {
          type: 'exercise',
          exerciseIds: ['b2-03-ex-01', 'b2-03-ex-02', 'b2-03-ex-03', 'b2-03-ex-04', 'b2-03-ex-05'],
        },
        {
          type: 'summary',
          title: 'Quick recap',
          bullets: ['Name the source', 'Ask what evidence is missing'],
        },
      ],
    },
    {
      id: 'b2-03-l2',
      title: 'Writing a critical note',
      objective: 'Summarise and critique a short article.',
      steps: [
        {
          type: 'explanation',
          title: 'Summary then judgement',
          body: 'First samenvatten neutrally, then add critique: eenzijdig, impliciet, of goed onderbouwd. Keep tone professional.',
        },
        {
          type: 'examples',
          title: 'In context',
          items: [
            { nl: 'Het artikel vat het conflict samen, maar mist nuance.', en: 'The article summarises the conflict but lacks nuance.' },
            { nl: 'Desinformatie verspreidt zich sneller dan correcties.', en: 'Disinformation spreads faster than corrections.' }
          ],
        },
        {
          type: 'vocabulary',
          title: 'Key words',
          vocabularyIds: ['vocab-b2-458', 'vocab-b2-459', 'vocab-b2-453', 'vocab-b2-454', 'vocab-b2-444', 'vocab-b2-440'],
        },
        {
          type: 'exercise',
          exerciseIds: ['b2-03-ex-06', 'b2-03-ex-07', 'b2-03-ex-08', 'b2-03-ex-09', 'b2-03-ex-10'],
        },
        {
          type: 'summary',
          title: 'Quick recap',
          bullets: ['Neutral summary first', 'Then evaluate evidence'],
        },
      ],
    }
  ],
  lessonExercises,
  checkpoint,
);

export const moduleB203Exercises = lessonExercises;
