import type { Assessment } from '../types';

export const assessments: Assessment[] = [
  {
    id: 'assessment-placement',
    title: 'Placement check',
    titleNl: 'Niveautest (kort)',
    description:
      'Short multi-skill check to suggest a starting level (Pre-A1 through B2). Not an official exam.',
    kind: 'placement',
    questions: [
      {
        id: 'placement-q01',
        type: 'multiple-choice',
        prompt: 'Welke groet gebruik je \'s ochtends?',
        promptEn: 'Which greeting do you use in the morning?',
        options: ['Goedenacht', 'Goedemorgen', 'Goedenavond', 'Doei'],
        acceptedAnswers: ['Goedemorgen'],
        explanation: 'Goedemorgen = good morning.',
        skill: 'vocabulary',
        level: 'pre-a1',
        difficulty: 1,
      },
      {
        id: 'placement-q02',
        type: 'multiple-choice',
        prompt: 'Ik ___ uit Portugal.',
        promptEn: 'I ___ from Portugal.',
        options: ['ben', 'kom', 'heb', 'ga'],
        acceptedAnswers: ['kom'],
        explanation: 'Ik kom uit + land.',
        skill: 'grammar',
        level: 'a1',
        difficulty: 1,
      },
      {
        id: 'placement-q03',
        type: 'translation-en-nl',
        prompt: 'Translate: I live in Haarlem.',
        acceptedAnswers: ['Ik woon in Haarlem.', 'Ik woon in Haarlem'],
        explanation: 'Wonen + in + plaats.',
        skill: 'writing',
        level: 'a1',
        difficulty: 2,
      },
      {
        id: 'placement-q04',
        type: 'multiple-choice',
        prompt: 'Gisteren ___ ik naar de markt.',
        promptEn: 'Yesterday I ___ to the market.',
        options: ['ga', 'ben gegaan', 'ging', 'gaan'],
        acceptedAnswers: ['ben gegaan'],
        explanation: 'Perfectum: zijn + gegaan (beweging).',
        skill: 'grammar',
        level: 'a2',
        difficulty: 2,
      },
      {
        id: 'placement-q05',
        type: 'reading-comp',
        prompt: 'Waarom belt Eva?',
        passage:
          'Eva: Hoi Tom, ik ben ziek vandaag. Kun jij de vergadering notuleren? Tom: Natuurlijk, beterschap!',
        options: [
          'Ze vraagt Tom om notulen te maken.',
          'Ze wil eten bestellen.',
          'Ze zoekt een hotel.',
          'Ze verhuist.',
        ],
        acceptedAnswers: ['Ze vraagt Tom om notulen te maken.'],
        explanation: 'Eva is ziek en vraagt om hulp met notuleren.',
        skill: 'reading',
        level: 'b1',
        difficulty: 2,
      },
    ],
  },
  {
    id: 'assessment-a1-end',
    title: 'A1 review',
    titleNl: 'A1-eindcheck',
    description: 'Review A1 themes: daily life, shopping, directions and basic grammar.',
    kind: 'level-end',
    targetLevel: 'a1',
    questions: [
      {
        id: 'a1-end-q01',
        type: 'multiple-choice',
        prompt: 'Negatie: Ik drink ___ melk.',
        options: ['niet', 'geen', 'niet de', 'geen de'],
        acceptedAnswers: ['geen'],
        explanation: 'Geen + onbepaald zelfstandig naamwoord.',
        skill: 'grammar',
        level: 'a1',
        difficulty: 2,
      },
      {
        id: 'a1-end-q02',
        type: 'multiple-choice',
        prompt: 'Waar is het station?',
        promptEn: 'Where is the station?',
        options: ['Rechts om de hoek.', 'Ik ben moe.', 'Twee euro.', 'Maandag.'],
        acceptedAnswers: ['Rechts om de hoek.'],
        explanation: 'Antwoord geeft route/locatie.',
        skill: 'speaking',
        level: 'a1',
        difficulty: 1,
      },
      {
        id: 'a1-end-q03',
        type: 'translation-nl-en',
        prompt: 'Vertaal: De koffie is warm.',
        acceptedAnswers: ['The coffee is warm.', 'The coffee is hot.'],
        explanation: 'Warm = warm; hot coffee can be warm or hot in English.',
        skill: 'writing',
        level: 'a1',
        difficulty: 1,
      },
      {
        id: 'a1-end-q04',
        type: 'listening',
        prompt: 'Wat bestelt de klant?',
        audioText: 'Goedemiddag, ik wil een broodje kaas en een glas water, alsjeblieft.',
        options: ['Broodje kaas en water', 'Pizza en bier', 'Alleen thee', 'Soep'],
        acceptedAnswers: ['Broodje kaas en water'],
        explanation: 'Broodje kaas + glas water.',
        skill: 'listening',
        level: 'a1',
        difficulty: 2,
      },
      {
        id: 'a1-end-q05',
        type: 'fill-blank',
        prompt: 'Wij ___ elke dag om zeven uur.',
        acceptedAnswers: ['staan op'],
        explanation: 'Opstaan: wij staan op.',
        skill: 'grammar',
        level: 'a1',
        difficulty: 2,
      },
    ],
  },
  {
    id: 'assessment-a2-end',
    title: 'A2 review',
    titleNl: 'A2-eindcheck',
    description: 'Past tense, appointments, travel and messages at A2.',
    kind: 'level-end',
    targetLevel: 'a2',
    questions: [
      {
        id: 'a2-end-q01',
        type: 'multiple-choice',
        prompt: 'Vorige week ___ ik een nieuwe baan.',
        options: ['heb gevonden', 'ben gevonden', 'vind', 'vond'],
        acceptedAnswers: ['heb gevonden'],
        explanation: 'Perfectum met hebben + voltooid deelwoord.',
        skill: 'grammar',
        level: 'a2',
        difficulty: 2,
      },
      {
        id: 'a2-end-q02',
        type: 'multiple-choice',
        prompt: 'Hotel: inchecken betekent …',
        options: ['arrive and register', 'leave the hotel', 'order food', 'buy tickets'],
        acceptedAnswers: ['arrive and register'],
        explanation: 'Inchecken = check in.',
        skill: 'vocabulary',
        level: 'a2',
        difficulty: 1,
      },
      {
        id: 'a2-end-q03',
        type: 'error-correction',
        prompt: 'Verbeter: Ik ben gisteren ga winkelen.',
        acceptedAnswers: ['Ik ben gisteren gaan winkelen.'],
        explanation: 'Infinitief met -n na zijn/hebben.',
        skill: 'writing',
        level: 'a2',
        difficulty: 2,
      },
      {
        id: 'a2-end-q04',
        type: 'reading-comp',
        prompt: 'Wanneer is de afspraak?',
        passage: 'Beste huisartsenpost, graag een afspraak voor mijn hoest. Donderdagmiddag past het best.',
        options: ['Donderdagmiddag', 'Maandagochtend', 'Vrijdagavond', 'Onbekend'],
        acceptedAnswers: ['Donderdagmiddag'],
        explanation: 'Expliciet genoemd in de tekst.',
        skill: 'reading',
        level: 'a2',
        difficulty: 2,
      },
      {
        id: 'a2-end-q05',
        type: 'translation-en-nl',
        prompt: 'Translate: Could you reply today?',
        acceptedAnswers: [
          'Kun je vandaag antwoorden?',
          'Kunt u vandaag antwoorden?',
        ],
        explanation: 'Kunnen + antwoorden.',
        skill: 'writing',
        level: 'a2',
        difficulty: 2,
      },
    ],
  },
  {
    id: 'assessment-b1-end',
    title: 'B1 review',
    titleNl: 'B1-eindcheck',
    description: 'Opinions, work communication, news and formal contact at B1.',
    kind: 'level-end',
    targetLevel: 'b1',
    questions: [
      {
        id: 'b1-end-q01',
        type: 'multiple-choice',
        prompt: 'Kies de beste linker: __ het regent, ga ik toch fietsen.',
        options: ['Hoewel', 'Omdat', 'Dat', 'Wanneer'],
        acceptedAnswers: ['Hoewel'],
        explanation: 'Hoewel = although (tegenstelling).',
        skill: 'grammar',
        level: 'b1',
        difficulty: 2,
      },
      {
        id: 'b1-end-q02',
        type: 'multiple-choice',
        prompt: 'Formeel: begin een e-mail met …',
        options: ['Hoi!', 'Geachte heer/mevrouw,', 'Doei', 'Yo'],
        acceptedAnswers: ['Geachte heer/mevrouw,'],
        explanation: 'Formele aanhef.',
        skill: 'writing',
        level: 'b1',
        difficulty: 1,
      },
      {
        id: 'b1-end-q03',
        type: 'reading-comp',
        prompt: 'Wat is de hoofdgedachte?',
        passage:
          'De gemeente wil meer fietsenstallingen bij het station. Bewoners reageren gemengd: sommigen vinden het nodig, anderen vrezen extra drukte.',
        options: [
          'Gemengde reacties op fietsenstallingen',
          'Iedereen is enthousiast',
          'Er komt geen station',
          'Fietsen worden verboden',
        ],
        acceptedAnswers: ['Gemengde reacties op fietsenstallingen'],
        explanation: 'Tekst noemt gemengde reacties.',
        skill: 'reading',
        level: 'b1',
        difficulty: 2,
      },
      {
        id: 'b1-end-q04',
        type: 'guided-writing',
        prompt: 'Schrijf 2–3 zinnen: geef je mening over thuiswerken.',
        modelAnswer:
          'Ik vind thuiswerken handig omdat ik tijd bespaar. Tegelijkertijd mis ik contact met collega\'s. Daarom wil ik deels op kantoor werken.',
        explanation: 'Gebruik meningswerkwoorden (vinden) en argument.',
        skill: 'writing',
        level: 'b1',
        difficulty: 3,
      },
      {
        id: 'b1-end-q05',
        type: 'multiple-choice',
        prompt: 'Zou + infinitief drukt uit …',
        options: ['Conditional / polite', 'Past perfect', 'Imperative', 'Plural'],
        acceptedAnswers: ['Conditional / polite'],
        explanation: 'Ik zou graag … = I would like …',
        skill: 'grammar',
        level: 'b1',
        difficulty: 2,
      },
    ],
  },
  {
    id: 'assessment-mixed',
    title: 'Mixed skills practice',
    titleNl: 'Gemengde oefening',
    description: 'Questions across levels for revision and confidence building.',
    kind: 'mixed',
    questions: [
      {
        id: 'mixed-q01',
        type: 'pronunciation',
        prompt: 'Oefen de klank in "huis".',
        audioText: 'huis',
        acceptedAnswers: ['huis'],
        explanation: 'Ui is één klank.',
        skill: 'pronunciation',
        level: 'pre-a1',
        difficulty: 1,
      },
      {
        id: 'mixed-q02',
        type: 'matching',
        prompt: 'Koppel de woorden.',
        pairs: [
          { left: 'moeder', right: 'mother' },
          { left: 'broer', right: 'brother' },
          { left: 'kaas', right: 'cheese' },
        ],
        acceptedAnswers: ['moeder=mother,broer=brother,kaas=cheese'],
        explanation: 'Basisfamilie en eten.',
        skill: 'vocabulary',
        level: 'a1',
        difficulty: 1,
      },
      {
        id: 'mixed-q03',
        type: 'sentence-order',
        prompt: 'Zet in de juiste volgorde.',
        orderItems: ['morgen', 'Ik', 'naar', 'ga', 'werk', '.'],
        acceptedAnswers: ['Ik ga morgen naar werk.'],
        explanation: 'SVO met tijd vroeg in zin mogelijk.',
        skill: 'grammar',
        level: 'a2',
        difficulty: 2,
      },
      {
        id: 'mixed-q04',
        type: 'dialogue',
        prompt: 'A: Mag ik de rekening? — B: …',
        acceptedAnswers: [
          'Natuurlijk, alstublieft.',
          'Ja, komt eraan.',
        ],
        explanation: 'Beleefd antwoord in restaurant.',
        skill: 'speaking',
        level: 'a2',
        difficulty: 2,
      },
      {
        id: 'mixed-q05',
        type: 'dictation',
        prompt: 'Schrijf wat je hoort.',
        audioText: 'De vergadering begint om half tien.',
        acceptedAnswers: ['De vergadering begint om half tien.'],
        explanation: 'Half tien = 9:30 in Netherlands Dutch.',
        skill: 'listening',
        level: 'b1',
        difficulty: 2,
      },
    ],
  },
  {
    id: 'assessment-b2-end',
    title: 'B2 review',
    titleNl: 'B2-eindcheck',
    description:
      'Upper-intermediate check: nuanced argument, connectors, media literacy, and workplace language. Not an official CEFR exam.',
    kind: 'level-end',
    targetLevel: 'b2',
    questions: [
      {
        id: 'b2-end-q01',
        type: 'multiple-choice',
        prompt: 'Hoewel het duur is, koop ik het. “Hoewel” introduceert…',
        options: [
          'een toegevende bijzin',
          'alleen een vraag',
          'een gebiedende wijs',
          'een lidwoord',
        ],
        acceptedAnswers: ['een toegevende bijzin'],
        explanation: 'Hoewel = although (concessive clause).',
        skill: 'grammar',
        level: 'b2',
        difficulty: 3,
      },
      {
        id: 'b2-end-q02',
        type: 'fill-blank',
        prompt: 'We gaan akkoord, _____ de voorwaarden duidelijk zijn.',
        acceptedAnswers: ['mits'],
        explanation: 'Mits = provided that.',
        skill: 'grammar',
        level: 'b2',
        difficulty: 3,
      },
      {
        id: 'b2-end-q03',
        type: 'reading-comp',
        prompt: 'Wat doet de schrijver?',
        passage:
          'Enerzijds is digitaal werken flexibel. Anderzijds vraagt het discipline. Uiteindelijk hangt succes af van duidelijke afspraken.',
        options: [
          'Weegt twee kanten af en trekt een conclusie',
          'Vertelt alleen een grap',
          'Geeft een recept',
          'Vraagt om een hotel',
        ],
        acceptedAnswers: ['Weegt twee kanten af en trekt een conclusie'],
        explanation: 'Enerzijds/anderzijds + uiteindelijk = balanced argument.',
        skill: 'reading',
        level: 'b2',
        difficulty: 3,
      },
      {
        id: 'b2-end-q04',
        type: 'translation-en-nl',
        prompt: 'Translate: Check your sources.',
        acceptedAnswers: [
          'Controleer je bronnen.',
          'Controleer jouw bronnen.',
          'Controleer uw bronnen.',
        ],
        explanation: 'Bronnen controleren is kern van medialwijsheid.',
        skill: 'writing',
        level: 'b2',
        difficulty: 2,
      },
      {
        id: 'b2-end-q05',
        type: 'guided-writing',
        prompt:
          'Schrijf 4–5 zinnen: jouw standpunt over thuiswerken, één tegenargument, en een conclusie met een B2-connector.',
        modelAnswer:
          'Mijn standpunt is dat hybride werken goed kan werken. Een tegenargument is minder informeel contact. Desalniettemin helpen vaste overlegmomenten. Daarom steun ik een duidelijke hybride regeling.',
        checklist: [
          'Standpunt',
          'Tegenargument',
          'B2-connector (bijv. desalniettemin/enerzijds)',
          'Conclusie',
        ],
        explanation: 'Self-assess against the checklist — not auto-scored for style.',
        skill: 'writing',
        level: 'b2',
        difficulty: 3,
      },
    ],
  },
];
