import { buildVocab } from './buildItem';
import type { VocabularyItem } from '../types';

export const vocabularyA1Items: VocabularyItem[] = [
  buildVocab('vocab-a1-081', 'adres', 'address', 'noun', 'a1', 'personal', 'Mijn adres is Kerkstraat 12.', 'My address is Kerkstraat 12.', { article: 'het', plural: 'adressen' }),
  buildVocab('vocab-a1-082', 'telefoonnummer', 'phone number', 'noun', 'a1', 'personal', 'Wat is je telefoonnummer?', 'What is your phone number?', { article: 'het', plural: 'telefoonnummers' }),
  buildVocab('vocab-a1-083', 'e-mailadres', 'email address', 'noun', 'a1', 'personal', 'Stuur me je e-mailadres.', 'Send me your email address.', { article: 'het', plural: 'e-mailadressen' }),
  buildVocab('vocab-a1-084', 'leeftijd', 'age', 'noun', 'a1', 'personal', 'Wat is je leeftijd?', 'What is your age?', { article: 'de', plural: 'leeftijden' }),
  buildVocab('vocab-a1-085', 'nationaliteit', 'nationality', 'noun', 'a1', 'personal', 'Mijn nationaliteit is Nederlands.', 'My nationality is Dutch.', { article: 'de', plural: 'nationaliteiten' }),
  buildVocab('vocab-a1-086', 'getrouwd', 'married', 'adjective', 'a1', 'personal', 'Ik ben getrouwd.', 'I am married.'),
  buildVocab('vocab-a1-087', 'alleenstaand', 'single', 'adjective', 'a1', 'personal', 'Ze is alleenstaand.', 'She is single.'),
  buildVocab('vocab-a1-088', 'moeder', 'mother', 'noun', 'a1', 'family', 'Mijn moeder woont in Leeuwarden.', 'My mother lives in Leeuwarden.', { article: 'de', plural: 'moeders' }),
  buildVocab('vocab-a1-089', 'vader', 'father', 'noun', 'a1', 'family', 'Zijn vader is docent.', 'His father is a teacher.', { article: 'de', plural: 'vaders' }),
  buildVocab('vocab-a1-090', 'broer', 'brother', 'noun', 'a1', 'family', 'Ik heb één broer.', 'I have one brother.', { article: 'de', plural: 'broers' }),
  buildVocab('vocab-a1-091', 'zus', 'sister', 'noun', 'a1', 'family', 'Mijn zus studeert geneeskunde.', 'My sister studies medicine.', { article: 'de', plural: 'zussen' }),
  buildVocab('vocab-a1-092', 'kind', 'child', 'noun', 'a1', 'family', 'Het kind speelt buiten.', 'The child plays outside.', { article: 'het', plural: 'kinderen' }),
  buildVocab('vocab-a1-093', 'opa', 'grandpa', 'noun', 'a1', 'family', 'Opa vertelt grappige verhalen.', 'Grandpa tells funny stories.', { article: 'de', plural: 'opa\'s' }),
  buildVocab('vocab-a1-094', 'oma', 'grandma', 'noun', 'a1', 'family', 'Oma bakt appeltaart.', 'Grandma bakes apple pie.', { article: 'de', plural: 'oma\'s' }),
  buildVocab('vocab-a1-095', 'partner', 'partner', 'noun', 'a1', 'family', 'Mijn partner werkt parttime.', 'My partner works part-time.', { article: 'de', plural: 'partners' }),
  buildVocab('vocab-a1-096', 'huis', 'house / home', 'noun', 'a1', 'home', 'Ons huis heeft een tuin.', 'Our house has a garden.', { article: 'het', plural: 'huizen' }),
  buildVocab('vocab-a1-097', 'appartement', 'apartment', 'noun', 'a1', 'home', 'Ik woon in een appartement.', 'I live in an apartment.', { article: 'het', plural: 'appartementen' }),
  buildVocab('vocab-a1-098', 'keuken', 'kitchen', 'noun', 'a1', 'home', 'De keuken is schoon.', 'The kitchen is clean.', { article: 'de', plural: 'keukens' }),
  buildVocab('vocab-a1-099', 'slaapkamer', 'bedroom', 'noun', 'a1', 'home', 'De slaapkamer is op de eerste verdieping.', 'The bedroom is on the first floor.', { article: 'de', plural: 'slaapkamers' }),
  buildVocab('vocab-a1-100', 'badkamer', 'bathroom', 'noun', 'a1', 'home', 'De badkamer heeft een douche.', 'The bathroom has a shower.', { article: 'de', plural: 'badkamers' }),
  buildVocab('vocab-a1-101', 'woonkamer', 'living room', 'noun', 'a1', 'home', 'We zitten in de woonkamer.', 'We sit in the living room.', { article: 'de', plural: 'woonkamers' }),
  buildVocab('vocab-a1-102', 'tuin', 'garden', 'noun', 'a1', 'home', 'De tuin is groot.', 'The garden is big.', { article: 'de', plural: 'tuinen' }),
  buildVocab('vocab-a1-103', 'bank', 'sofa', 'noun', 'a1', 'home', 'De kat ligt op de bank.', 'The cat lies on the sofa.', { article: 'de', plural: 'banken' }),
  buildVocab('vocab-a1-104', 'tafel', 'table', 'noun', 'a1', 'home', 'Zet de borden op tafel.', 'Put the plates on the table.', { article: 'de', plural: 'tafels' }),
  buildVocab('vocab-a1-105', 'stoel', 'chair', 'noun', 'a1', 'home', 'Deze stoel is comfortabel.', 'This chair is comfortable.', { article: 'de', plural: 'stoelen' }),
  buildVocab('vocab-a1-106', 'raam', 'window', 'noun', 'a1', 'home', 'Doe het raam open.', 'Open the window.', { article: 'het', plural: 'ramen' }),
  buildVocab('vocab-a1-107', 'deur', 'door', 'noun', 'a1', 'home', 'De deur is dicht.', 'The door is closed.', { article: 'de', plural: 'deuren' }),
  buildVocab('vocab-a1-108', 'opstaan', 'to get up', 'verb', 'a1', 'routine', 'Ik sta om zeven uur op.', 'I get up at seven.'),
  buildVocab('vocab-a1-109', 'ontbijten', 'to have breakfast', 'verb', 'a1', 'routine', 'We ontbijten samen.', 'We have breakfast together.'),
  buildVocab('vocab-a1-110', 'werken', 'to work', 'verb', 'a1', 'routine', 'Ik werk van negen tot vijf.', 'I work from nine to five.'),
  buildVocab('vocab-a1-111', 'lunch', 'lunch', 'noun', 'a1', 'routine', 'Tijdens lunch lees ik even.', 'During lunch I read briefly.', { article: 'de' }),
  buildVocab('vocab-a1-112', 'koken', 'to cook', 'verb', 'a1', 'routine', 'Vanavond kook ik pasta.', 'Tonight I cook pasta.'),
  buildVocab('vocab-a1-113', 'afwassen', 'to do the dishes', 'verb', 'a1', 'routine', 'Na het eten was ik af.', 'After eating I do the dishes.'),
  buildVocab('vocab-a1-114', 'slapen', 'to sleep', 'verb', 'a1', 'routine', 'Ik slaap acht uur per nacht.', 'I sleep eight hours a night.'),
  buildVocab('vocab-a1-115', 'brood', 'bread', 'noun', 'a1', 'food', 'Ik eet bruin brood.', 'I eat brown bread.', { article: 'het' }),
  buildVocab('vocab-a1-116', 'kaas', 'cheese', 'noun', 'a1', 'food', 'Nederlanders houden van kaas.', 'Dutch people love cheese.', { article: 'de' }),
  buildVocab('vocab-a1-117', 'melk', 'milk', 'noun', 'a1', 'food', 'Wil je melk in je koffie?', 'Do you want milk in your coffee?', { article: 'de' }),
  buildVocab('vocab-a1-118', 'koffie', 'coffee', 'noun', 'a1', 'food', 'Zullen we koffie drinken?', 'Shall we drink coffee?', { article: 'de' }),
  buildVocab('vocab-a1-119', 'thee', 'tea', 'noun', 'a1', 'food', 'Ik drink groene thee.', 'I drink green tea.', { article: 'de' }),
  buildVocab('vocab-a1-120', 'water', 'water', 'noun', 'a1', 'food', 'Mag ik een glas water?', 'May I have a glass of water?', { article: 'het' }),
  buildVocab('vocab-a1-121', 'appel', 'apple', 'noun', 'a1', 'food', 'De appel is zoet.', 'The apple is sweet.', { article: 'de', plural: 'appels' }),
  buildVocab('vocab-a1-122', 'banaan', 'banana', 'noun', 'a1', 'food', 'Een banaan is gezond.', 'A banana is healthy.', { article: 'de', plural: 'bananen' }),
  buildVocab('vocab-a1-123', 'groente', 'vegetable', 'noun', 'a1', 'food', 'Ik eet veel groente.', 'I eat a lot of vegetables.', { article: 'de', plural: 'groenten' }),
  buildVocab('vocab-a1-124', 'vlees', 'meat', 'noun', 'a1', 'food', 'Vandaag eet ik geen vlees.', 'Today I eat no meat.', { article: 'het' }),
  buildVocab('vocab-a1-125', 'vis', 'fish', 'noun', 'a1', 'food', 'Op vrijdag eten we vis.', 'On Friday we eat fish.', { article: 'de' }),
  buildVocab('vocab-a1-126', 'supermarkt', 'supermarket', 'noun', 'a1', 'shopping', 'Ik ga naar de supermarkt.', 'I go to the supermarket.', { article: 'de', plural: 'supermarkten' }),
  buildVocab('vocab-a1-127', 'winkel', 'shop', 'noun', 'a1', 'shopping', 'De winkel is om de hoek.', 'The shop is around the corner.', { article: 'de', plural: 'winkels' }),
  buildVocab('vocab-a1-128', 'prijs', 'price', 'noun', 'a1', 'shopping', 'Wat is de prijs?', 'What is the price?', { article: 'de', plural: 'prijzen' }),
  buildVocab('vocab-a1-129', 'euro', 'euro', 'noun', 'a1', 'shopping', 'Het kost vijf euro.', 'It costs five euros.', { article: 'de', plural: 'euro\'s' }),
  buildVocab('vocab-a1-130', 'bon', 'receipt', 'noun', 'a1', 'shopping', 'Bewaar de bon.', 'Keep the receipt.', { article: 'de', plural: 'bonnen' }),
  buildVocab('vocab-a1-131', 'contant', 'cash', 'adjective', 'a1', 'shopping', 'Betaal je contant of met pin?', 'Do you pay cash or by card?'),
  buildVocab('vocab-a1-132', 'pinpas', 'debit card', 'noun', 'a1', 'shopping', 'Ik betaal met mijn pinpas.', 'I pay with my debit card.', { article: 'de', plural: 'pinpassen' }),
  buildVocab('vocab-a1-133', 'stad', 'city', 'noun', 'a1', 'town', 'Amsterdam is een grote stad.', 'Amsterdam is a big city.', { article: 'de', plural: 'steden' }),
  buildVocab('vocab-a1-134', 'straat', 'street', 'noun', 'a1', 'town', 'Welke straat is dit?', 'Which street is this?', { article: 'de', plural: 'straten' }),
  buildVocab('vocab-a1-135', 'plein', 'square', 'noun', 'a1', 'town', 'We ontmoeten elkaar op het plein.', 'We meet on the square.', { article: 'het', plural: 'pleinen' }),
  buildVocab('vocab-a1-136', 'station', 'station', 'noun', 'a1', 'transport', 'Het station is dichtbij.', 'The station is nearby.', { article: 'het', plural: 'stations' }),
  buildVocab('vocab-a1-137', 'bus', 'bus', 'noun', 'a1', 'transport', 'De bus komt om tien uur.', 'The bus comes at ten.', { article: 'de', plural: 'bussen' }),
  buildVocab('vocab-a1-138', 'trein', 'train', 'noun', 'a1', 'transport', 'De trein heeft vertraging.', 'The train is delayed.', { article: 'de', plural: 'treinen' }),
  buildVocab('vocab-a1-139', 'fiets', 'bicycle', 'noun', 'a1', 'transport', 'Ik ga met de fiets.', 'I go by bike.', { article: 'de', plural: 'fietsen' }),
  buildVocab('vocab-a1-140', 'links', 'left', 'adverb', 'a1', 'directions', 'Ga links bij het stoplicht.', 'Turn left at the traffic lights.'),
  buildVocab('vocab-a1-141', 'rechts', 'right', 'adverb', 'a1', 'directions', 'Het café is rechts.', 'The café is on the right.'),
  buildVocab('vocab-a1-142', 'rechtdoor', 'straight ahead', 'adverb', 'a1', 'directions', 'Loop rechtdoor tot de brug.', 'Walk straight ahead until the bridge.'),
  buildVocab('vocab-a1-143', 'baan', 'job', 'noun', 'a1', 'work', 'Ik zoek een nieuwe baan.', 'I am looking for a new job.', { article: 'de', plural: 'banen' }),
  buildVocab('vocab-a1-144', 'kantoor', 'office', 'noun', 'a1', 'work', 'Het kantoor is in Rotterdam.', 'The office is in Rotterdam.', { article: 'het', plural: 'kantoren' }),
  buildVocab('vocab-a1-145', 'collega', 'colleague', 'noun', 'a1', 'work', 'Mijn collega helpt me.', 'My colleague helps me.', { article: 'de', plural: 'collega\'s' }),
  buildVocab('vocab-a1-146', 'studie', 'study / degree', 'noun', 'a1', 'study', 'Ik doe een studie economie.', 'I am doing a degree in economics.', { article: 'de', plural: 'studies' }),
  buildVocab('vocab-a1-147', 'universiteit', 'university', 'noun', 'a1', 'study', 'Ze studeert aan de universiteit.', 'She studies at the university.', { article: 'de', plural: 'universiteiten' }),
  buildVocab('vocab-a1-148', 'hobby', 'hobby', 'noun', 'a1', 'hobbies', 'Lezen is mijn hobby.', 'Reading is my hobby.', { article: 'de', plural: 'hobby\'s' }),
  buildVocab('vocab-a1-149', 'voetbal', 'football', 'noun', 'a1', 'hobbies', 'Ik kijk graag voetbal.', 'I like watching football.', { article: 'het' }),
  buildVocab('vocab-a1-150', 'muziek', 'music', 'noun', 'a1', 'hobbies', 'Ik luister naar Nederlandse muziek.', 'I listen to Dutch music.', { article: 'de' }),
  buildVocab('vocab-a1-151', 'weer', 'weather', 'noun', 'a1', 'weather', 'Het weer is mooi vandaag.', 'The weather is nice today.', { article: 'het' }),
  buildVocab('vocab-a1-152', 'regen', 'rain', 'noun', 'a1', 'weather', 'Ik neem een paraplu vanwege de regen.', 'I take an umbrella because of the rain.', { article: 'de' }),
  buildVocab('vocab-a1-153', 'zon', 'sun', 'noun', 'a1', 'weather', 'De zon schijnt.', 'The sun is shining.', { article: 'de' }),
  buildVocab('vocab-a1-154', 'jas', 'coat', 'noun', 'a1', 'clothing', 'Draag een warme jas.', 'Wear a warm coat.', { article: 'de', plural: 'jassen' }),
  buildVocab('vocab-a1-155', 'schoenen', 'shoes', 'noun', 'a1', 'clothing', 'Mijn schoenen zijn nat.', 'My shoes are wet.', { article: 'de', plural: 'schoenen' }),
  buildVocab('vocab-a1-156', 'hoofdpijn', 'headache', 'noun', 'a1', 'health', 'Ik heb hoofdpijn.', 'I have a headache.', { article: 'de' }),
  buildVocab('vocab-a1-157', 'dokter', 'doctor', 'noun', 'a1', 'health', 'Ik maak een afspraak bij de dokter.', 'I make an appointment with the doctor.', { article: 'de', plural: 'dokters' }),
  buildVocab('vocab-a1-158', 'apotheek', 'pharmacy', 'noun', 'a1', 'health', 'Je medicijn ligt bij de apotheek.', 'Your medicine is at the pharmacy.', { article: 'de', plural: 'apotheken' }),
  buildVocab('vocab-a1-159', 'ziek', 'ill', 'adjective', 'a1', 'health', 'Hij is ziek vandaag.', 'He is ill today.'),
  buildVocab('vocab-a1-160', 'beter', 'better', 'adjective', 'a1', 'health', 'Ik voel me beter.', 'I feel better.'),
  buildVocab('vocab-a1-161', 'hebben', 'to have', 'verb', 'a1', 'grammar', 'Ik heb een vraag.', 'I have a question.'),
  buildVocab('vocab-a1-162', 'zijn', 'to be', 'verb', 'a1', 'grammar', 'Ik ben student.', 'I am a student.'),
  buildVocab('vocab-a1-163', 'gaan', 'to go', 'verb', 'a1', 'grammar', 'We gaan naar huis.', 'We go home.'),
  buildVocab('vocab-a1-164', 'willen', 'to want', 'verb', 'a1', 'grammar', 'Ik wil Nederlands leren.', 'I want to learn Dutch.'),
  buildVocab('vocab-a1-165', 'mogen', 'may / to be allowed', 'verb', 'a1', 'grammar', 'Mag ik hier zitten?', 'May I sit here?'),
  buildVocab('vocab-a1-166', 'kunnen', 'can', 'verb', 'a1', 'grammar', 'Kun je me helpen?', 'Can you help me?'),
  buildVocab('vocab-a1-167', 'moeten', 'must / have to', 'verb', 'a1', 'grammar', 'Ik moet werken.', 'I have to work.'),
  buildVocab('vocab-a1-168', 'niet', 'not', 'adverb', 'a1', 'grammar', 'Ik begrijp het niet.', 'I do not understand.'),
  buildVocab('vocab-a1-169', 'geen', 'no / not a', 'determiner', 'a1', 'grammar', 'Ik drink geen alcohol.', 'I do not drink alcohol.'),
  buildVocab('vocab-a1-170', 'de', 'the (common)', 'determiner', 'a1', 'grammar', 'De man leest de krant.', 'The man reads the newspaper.'),
  buildVocab('vocab-a1-171', 'het', 'the (neuter)', 'determiner', 'a1', 'grammar', 'Het kind speelt buiten.', 'The child plays outside.'),
  buildVocab('vocab-a1-172', 'mijn', 'my', 'pronoun', 'a1', 'grammar', 'Dit is mijn tas.', 'This is my bag.'),
  buildVocab('vocab-a1-173', 'jouw', 'your', 'pronoun', 'a1', 'grammar', 'Is dit jouw fiets?', 'Is this your bike?'),
  buildVocab('vocab-a1-174', 'onze', 'our', 'pronoun', 'a1', 'grammar', 'Onze les begint zo.', 'Our lesson starts soon.'),
  buildVocab('vocab-a1-175', 'veel', 'many / much', 'adjective', 'a1', 'grammar', 'Ik heb veel werk.', 'I have a lot of work.'),
  buildVocab('vocab-a1-176', 'weinig', 'little / few', 'adjective', 'a1', 'grammar', 'Er is weinig tijd.', 'There is little time.'),
  buildVocab('vocab-a1-177', 'groot', 'big', 'adjective', 'a1', 'grammar', 'Het huis is groot.', 'The house is big.'),
  buildVocab('vocab-a1-178', 'klein', 'small', 'adjective', 'a1', 'grammar', 'De hond is klein.', 'The dog is small.'),
  buildVocab('vocab-a1-179', 'goed', 'good', 'adjective', 'a1', 'grammar', 'Dat is een goed idee.', 'That is a good idea.'),
  buildVocab('vocab-a1-180', 'slecht', 'bad', 'adjective', 'a1', 'grammar', 'Het weer is slecht.', 'The weather is bad.'),
  buildVocab('vocab-a1-181', 'nieuw', 'new', 'adjective', 'a1', 'grammar', 'Ik heb een nieuwe telefoon.', 'I have a new phone.'),
  buildVocab('vocab-a1-182', 'oud', 'old', 'adjective', 'a1', 'grammar', 'Deze brug is oud.', 'This bridge is old.'),
  buildVocab('vocab-a1-183', 'mooi', 'beautiful / nice', 'adjective', 'a1', 'grammar', 'Wat een mooi park!', 'What a beautiful park!'),
  buildVocab('vocab-a1-184', 'leuk', 'nice / fun', 'adjective', 'a1', 'grammar', 'Het was een leuke avond.', 'It was a nice evening.'),
  buildVocab('vocab-a1-185', 'druk', 'busy', 'adjective', 'a1', 'grammar', 'Ik ben druk met studeren.', 'I am busy studying.'),
  buildVocab('vocab-a1-186', 'moe', 'tired', 'adjective', 'a1', 'grammar', 'Na het werk ben ik moe.', 'After work I am tired.'),
  buildVocab('vocab-a1-187', 'honger', 'hunger', 'noun', 'a1', 'food', 'Ik heb honger.', 'I am hungry.', { article: 'de' }),
  buildVocab('vocab-a1-188', 'dorst', 'thirst', 'noun', 'a1', 'food', 'Heb je dorst?', 'Are you thirsty?', { article: 'de' }),
  buildVocab('vocab-a1-189', 'menu', 'menu', 'noun', 'a1', 'food', 'Mag ik het menu?', 'May I have the menu?', { article: 'het', plural: 'menu\'s' }),
  buildVocab('vocab-a1-190', 'rekening', 'bill', 'noun', 'a1', 'food', 'De rekening, alsjeblieft.', 'The bill, please.', { article: 'de', plural: 'rekeningen' }),
  buildVocab('vocab-a1-191', 'markt', 'market', 'noun', 'a1', 'shopping', 'Op de markt koop ik groente.', 'At the market I buy vegetables.', { article: 'de', plural: 'markten' }),
  buildVocab('vocab-a1-192', 'kassa', 'checkout', 'noun', 'a1', 'shopping', 'Ga naar de kassa.', 'Go to the checkout.', { article: 'de', plural: 'kassa\'s' }),
  buildVocab('vocab-a1-193', 'ticket', 'ticket', 'noun', 'a1', 'transport', 'Ik koop een treinticket.', 'I buy a train ticket.', { article: 'het', plural: 'tickets' }),
  buildVocab('vocab-a1-194', 'halte', 'stop (bus/tram)', 'noun', 'a1', 'transport', 'De halte is voor het museum.', 'The stop is in front of the museum.', { article: 'de', plural: 'haltes' }),
  buildVocab('vocab-a1-195', 'brug', 'bridge', 'noun', 'a1', 'town', 'Over de brug zie je de kerk.', 'Across the bridge you see the church.', { article: 'de', plural: 'bruggen' }),
  buildVocab('vocab-a1-196', 'museum', 'museum', 'noun', 'a1', 'town', 'Het museum is gratis op zondag.', 'The museum is free on Sunday.', { article: 'het', plural: 'musea' }),
  buildVocab('vocab-a1-197', 'bibliotheek', 'library', 'noun', 'a1', 'study', 'Ik leen boeken in de bibliotheek.', 'I borrow books at the library.', { article: 'de', plural: 'bibliotheken' }),
  buildVocab('vocab-a1-198', 'taal', 'language', 'noun', 'a1', 'study', 'Nederlands is een mooie taal.', 'Dutch is a beautiful language.', { article: 'de', plural: 'talen' }),
  buildVocab('vocab-a1-199', 'cursus', 'course', 'noun', 'a1', 'study', 'Ik volg een cursus Nederlands.', 'I take a Dutch course.', { article: 'de', plural: 'cursussen' }),
  buildVocab('vocab-a1-200', 'vakantie', 'holiday', 'noun', 'a1', 'hobbies', 'In de zomervakantie ga ik naar Zeeland.', 'In the summer holiday I go to Zeeland.', { article: 'de', plural: 'vakanties' }),
];
