import { buildVocab } from './buildItem';
import type { VocabularyItem } from '../types';

export const vocabularyA2Items: VocabularyItem[] = [
  buildVocab('vocab-a2-201', 'afspraak', 'appointment', 'noun', 'a2', 'plans', 'Ik heb een afspraak om drie uur.', 'I have an appointment at three.', { article: 'de', plural: 'afspraken' }),
  buildVocab('vocab-a2-202', 'agenda', 'diary / calendar', 'noun', 'a2', 'plans', 'Zet het in je agenda.', 'Put it in your calendar.', { article: 'de', plural: 'agenda\'s' }),
  buildVocab('vocab-a2-203', 'van plan zijn', 'to plan to', 'phrase', 'a2', 'plans', 'Ik ben van plan te verhuizen.', 'I plan to move.'),
  buildVocab('vocab-a2-204', 'misschien', 'maybe', 'adverb', 'a2', 'plans', 'Misschien ga ik mee.', 'Maybe I will come along.'),
  buildVocab('vocab-a2-205', 'waarschijnlijk', 'probably', 'adverb', 'a2', 'plans', 'Waarschijnlijk regent het morgen.', 'It will probably rain tomorrow.'),
  buildVocab('vocab-a2-206', 'hotel', 'hotel', 'noun', 'a2', 'travel', 'We slapen in een klein hotel.', 'We sleep in a small hotel.', { article: 'het', plural: 'hotels' }),
  buildVocab('vocab-a2-207', 'reservering', 'reservation', 'noun', 'a2', 'travel', 'Ik heb een reservering op naam Bakker.', 'I have a reservation under the name Bakker.', { article: 'de', plural: 'reserveringen' }),
  buildVocab('vocab-a2-208', 'paspoort', 'passport', 'noun', 'a2', 'travel', 'Vergeet je paspoort niet.', 'Do not forget your passport.', { article: 'het', plural: 'passpoorten' }),
  buildVocab('vocab-a2-209', 'koffer', 'suitcase', 'noun', 'a2', 'travel', 'Mijn koffer is te zwaar.', 'My suitcase is too heavy.', { article: 'de', plural: 'koffers' }),
  buildVocab('vocab-a2-210', 'vertrekken', 'to depart', 'verb', 'a2', 'travel', 'De trein vertrekt om acht uur.', 'The train departs at eight.'),
  buildVocab('vocab-a2-211', 'aankomen', 'to arrive', 'verb', 'a2', 'travel', 'We komen om middernacht aan.', 'We arrive at midnight.'),
  buildVocab('vocab-a2-212', 'verleden', 'past', 'noun', 'a2', 'past', 'In het verleden woonde ik in Brussel.', 'In the past I lived in Brussels.', { article: 'het' }),
  buildVocab('vocab-a2-213', 'ervaring', 'experience', 'noun', 'a2', 'past', 'Dat was een goede ervaring.', 'That was a good experience.', { article: 'de', plural: 'ervaringen' }),
  buildVocab('vocab-a2-214', 'gisteren', 'yesterday', 'adverb', 'a2', 'past', 'Gisteren was ik ziek.', 'Yesterday I was ill.'),
  buildVocab('vocab-a2-215', 'vorige week', 'last week', 'phrase', 'a2', 'past', 'Vorige week ben ik verhuisd.', 'Last week I moved.'),
  buildVocab('vocab-a2-216', 'huur', 'rent', 'noun', 'a2', 'housing', 'De huur is inclusief gas.', 'The rent includes gas.', { article: 'de' }),
  buildVocab('vocab-a2-217', 'huurcontract', 'rental contract', 'noun', 'a2', 'housing', 'Lees het huurcontract goed.', 'Read the rental contract carefully.', { article: 'het', plural: 'huurcontracten' }),
  buildVocab('vocab-a2-218', 'buren', 'neighbours', 'noun', 'a2', 'housing', 'Onze buren zijn aardig.', 'Our neighbours are nice.', { article: 'de', plural: 'buren' }),
  buildVocab('vocab-a2-219', 'lekkage', 'leak', 'noun', 'a2', 'housing', 'Er is lekkage in de badkamer.', 'There is a leak in the bathroom.', { article: 'de', plural: 'lekkages' }),
  buildVocab('vocab-a2-220', 'klacht', 'complaint', 'noun', 'a2', 'health', 'Ik dien een klacht in bij de huisarts.', 'I file a complaint with the GP.', { article: 'de', plural: 'klachten' }),
  buildVocab('vocab-a2-221', 'recept', 'prescription', 'noun', 'a2', 'health', 'Je hebt een recept nodig.', 'You need a prescription.', { article: 'het', plural: 'recepten' }),
  buildVocab('vocab-a2-222', 'medicijn', 'medicine', 'noun', 'a2', 'health', 'Neem het medicijn na het eten.', 'Take the medicine after eating.', { article: 'het', plural: 'medicijnen' }),
  buildVocab('vocab-a2-223', 'uitnodiging', 'invitation', 'noun', 'a2', 'social', 'Bedankt voor de uitnodiging.', 'Thanks for the invitation.', { article: 'de', plural: 'uitnodigingen' }),
  buildVocab('vocab-a2-224', 'feest', 'party', 'noun', 'a2', 'social', 'Het feest begint om acht uur.', 'The party starts at eight.', { article: 'het', plural: 'feesten' }),
  buildVocab('vocab-a2-225', 'restaurant', 'restaurant', 'noun', 'a2', 'food', 'Dit restaurant is vegetarisch.', 'This restaurant is vegetarian.', { article: 'het', plural: 'restaurants' }),
  buildVocab('vocab-a2-226', 'ober', 'waiter', 'noun', 'a2', 'food', 'De ober komt zo.', 'The waiter will come shortly.', { article: 'de', plural: 'ober\'s' }),
  buildVocab('vocab-a2-227', 'teleurstelling', 'disappointment', 'noun', 'a2', 'feelings', 'Wat een teleurstelling.', 'What a disappointment.', { article: 'de', plural: 'teleurstellingen' }),
  buildVocab('vocab-a2-228', 'trots', 'proud', 'adjective', 'a2', 'feelings', 'Ik ben trots op mijn resultaat.', 'I am proud of my result.'),
  buildVocab('vocab-a2-229', 'boos', 'angry', 'adjective', 'a2', 'feelings', 'Waarom ben je boos?', 'Why are you angry?'),
  buildVocab('vocab-a2-230', 'e-mail', 'email', 'noun', 'a2', 'communication', 'Ik stuur je een e-mail.', 'I will send you an email.', { article: 'de', plural: 'e-mails' }),
  buildVocab('vocab-a2-231', 'bericht', 'message', 'noun', 'a2', 'communication', 'Ik kreeg een bericht op mijn telefoon.', 'I got a message on my phone.', { article: 'het', plural: 'berichten' }),
  buildVocab('vocab-a2-232', 'antwoorden', 'to reply', 'verb', 'a2', 'communication', 'Kun je vandaag antwoorden?', 'Can you reply today?'),
  buildVocab('vocab-a2-233', 'bellen', 'to call', 'verb', 'a2', 'communication', 'Ik bel je vanavond.', 'I will call you tonight.'),
  buildVocab('vocab-a2-234', 'uitleggen', 'to explain', 'verb', 'a2', 'communication', 'Kun je dat uitleggen?', 'Can you explain that?'),
  buildVocab('vocab-a2-235', 'begrijpen', 'to understand', 'verb', 'a2', 'communication', 'Ik begrijp de opdracht.', 'I understand the assignment.'),
  buildVocab('vocab-a2-236', 'vergeten', 'to forget', 'verb', 'a2', 'past', 'Ik ben mijn sleutels vergeten.', 'I forgot my keys.'),
  buildVocab('vocab-a2-237', 'gebeuren', 'to happen', 'verb', 'a2', 'past', 'Wat is er gebeurd?', 'What happened?'),
  buildVocab('vocab-a2-238', 'geweest', 'been (participle)', 'verb', 'a2', 'past', 'Ik ben in Paris geweest.', 'I have been to Paris.'),
  buildVocab('vocab-a2-239', 'gemaakt', 'made / done', 'verb', 'a2', 'past', 'Ik heb huiswerk gemaakt.', 'I have done homework.'),
  buildVocab('vocab-a2-240', 'tegen', 'against / about', 'preposition', 'a2', 'grammar', 'We praten tegen elkaar.', 'We talk to each other.'),
  buildVocab('vocab-a2-241', 'fietsenmaker', 'fietsenmaker', 'noun', 'a2', 'a2-general', 'Voorbeeld: fietsenmaker in context.', 'Example: fietsenmaker in context.', { article: 'het' }),
  buildVocab('vocab-a2-242', 'verzekering', 'insurance', 'noun', 'a2', 'a2-general', 'Voorbeeld: verzekering in context.', 'Example: insurance in context.', { article: 'het' }),
  buildVocab('vocab-a2-243', 'polis', 'policy', 'noun', 'a2', 'a2-general', 'Voorbeeld: polis in context.', 'Example: policy in context.', { article: 'het' }),
  buildVocab('vocab-a2-244', 'schade', 'damage', 'noun', 'a2', 'a2-general', 'Voorbeeld: schade in context.', 'Example: damage in context.', { article: 'de' }),
  buildVocab('vocab-a2-245', 'ongeluk', 'accident', 'noun', 'a2', 'a2-general', 'Voorbeeld: ongeluk in context.', 'Example: accident in context.', { article: 'het' }),
  buildVocab('vocab-a2-246', 'file', 'traffic jam', 'noun', 'a2', 'a2-general', 'Voorbeeld: file in context.', 'Example: traffic jam in context.', { article: 'de' }),
  buildVocab('vocab-a2-247', 'omleiding', 'detour', 'noun', 'a2', 'a2-general', 'Voorbeeld: omleiding in context.', 'Example: detour in context.', { article: 'het' }),
  buildVocab('vocab-a2-248', 'platform', 'platform', 'noun', 'a2', 'a2-general', 'Voorbeeld: platform in context.', 'Example: platform in context.', { article: 'het' }),
  buildVocab('vocab-a2-249', 'instappen', 'to board', 'verb', 'a2', 'a2-general', 'Voorbeeld: instappen in context.', 'Example: to board in context.'),
  buildVocab('vocab-a2-250', 'uitstappen', 'to get off', 'verb', 'a2', 'a2-general', 'Voorbeeld: uitstappen in context.', 'Example: to get off in context.'),
  buildVocab('vocab-a2-251', ' overstappen', 'to transfer', 'noun', 'a2', 'a2-general', 'Voorbeeld:  overstappen in context.', 'Example: to transfer in context.', { article: 'het' }),
  buildVocab('vocab-a2-252', 'herinneren', 'to remember', 'verb', 'a2', 'a2-general', 'Voorbeeld: herinneren in context.', 'Example: to remember in context.'),
  buildVocab('vocab-a2-253', 'herinnering', 'memory', 'noun', 'a2', 'a2-general', 'Voorbeeld: herinnering in context.', 'Example: memory in context.', { article: 'het' }),
  buildVocab('vocab-a2-254', 'vroeger', 'formerly', 'noun', 'a2', 'a2-general', 'Voorbeeld: vroeger in context.', 'Example: formerly in context.', { article: 'het' }),
  buildVocab('vocab-a2-255', 'sinds', 'since', 'noun', 'a2', 'a2-general', 'Voorbeeld: sinds in context.', 'Example: since in context.', { article: 'het' }),
  buildVocab('vocab-a2-256', 'totdat', 'until', 'noun', 'a2', 'a2-general', 'Voorbeeld: totdat in context.', 'Example: until in context.', { article: 'het' }),
  buildVocab('vocab-a2-257', 'zodra', 'as soon as', 'noun', 'a2', 'a2-general', 'Voorbeeld: zodra in context.', 'Example: as soon as in context.', { article: 'het' }),
  buildVocab('vocab-a2-258', 'terwijl', 'while', 'noun', 'a2', 'a2-general', 'Voorbeeld: terwijl in context.', 'Example: while in context.', { article: 'het' }),
  buildVocab('vocab-a2-259', 'eigen', 'eigen', 'noun', 'a2', 'a2-general', 'Voorbeeld: eigen in context.', 'Example: eigen in context.', { article: 'het' }),
  buildVocab('vocab-a2-260', 'huurder', 'tenant', 'noun', 'a2', 'a2-general', 'Voorbeeld: huurder in context.', 'Example: tenant in context.', { article: 'het' }),
  buildVocab('vocab-a2-261', 'verhuurder', 'landlord', 'noun', 'a2', 'a2-general', 'Voorbeeld: verhuurder in context.', 'Example: landlord in context.', { article: 'het' }),
  buildVocab('vocab-a2-262', 'isolatie', 'insulation', 'noun', 'a2', 'a2-general', 'Voorbeeld: isolatie in context.', 'Example: insulation in context.', { article: 'de' }),
  buildVocab('vocab-a2-263', 'cv-ketel', 'boiler', 'noun', 'a2', 'a2-general', 'Voorbeeld: cv-ketel in context.', 'Example: boiler in context.', { article: 'het' }),
  buildVocab('vocab-a2-264', 'storing', 'malfunction', 'noun', 'a2', 'a2-general', 'Voorbeeld: storing in context.', 'Example: malfunction in context.', { article: 'het' }),
  buildVocab('vocab-a2-265', 'huisarts', 'GP', 'noun', 'a2', 'a2-general', 'Voorbeeld: huisarts in context.', 'Example: GP in context.', { article: 'het' }),
  buildVocab('vocab-a2-266', 'spoedeisende hulp', 'emergency room', 'noun', 'a2', 'a2-general', 'Voorbeeld: spoedeisende hulp in context.', 'Example: emergency room in context.', { article: 'het' }),
  buildVocab('vocab-a2-267', 'symptoom', 'symptom', 'noun', 'a2', 'a2-general', 'Voorbeeld: symptoom in context.', 'Example: symptom in context.', { article: 'het' }),
  buildVocab('vocab-a2-268', 'allergie', 'allergy', 'noun', 'a2', 'a2-general', 'Voorbeeld: allergie in context.', 'Example: allergy in context.', { article: 'de' }),
  buildVocab('vocab-a2-269', 'rust', 'n rest', 'noun', 'a2', 'a2-general', 'Voorbeeld: rust in context.', 'Example: n rest in context.', { article: 'het' }),
  buildVocab('vocab-a2-270', 'stress', 'stress', 'noun', 'a2', 'a2-general', 'Voorbeeld: stress in context.', 'Example: stress in context.', { article: 'het' }),
  buildVocab('vocab-a2-271', 'deadline', 'deadline', 'noun', 'a2', 'a2-general', 'Voorbeeld: deadline in context.', 'Example: deadline in context.', { article: 'de' }),
  buildVocab('vocab-a2-272', 'overwerk', 'overtime', 'noun', 'a2', 'a2-general', 'Voorbeeld: overwerk in context.', 'Example: overtime in context.', { article: 'het' }),
  buildVocab('vocab-a2-273', 'salaris', 'salary', 'noun', 'a2', 'a2-general', 'Voorbeeld: salaris in context.', 'Example: salary in context.', { article: 'het' }),
  buildVocab('vocab-a2-274', 'baan', 'vacancy', 'noun', 'a2', 'a2-general', 'Voorbeeld: baan in context.', 'Example: vacancy in context.', { article: 'het' }),
  buildVocab('vocab-a2-275', 'solliciteren', 'to apply', 'verb', 'a2', 'a2-general', 'Voorbeeld: solliciteren in context.', 'Example: to apply in context.'),
  buildVocab('vocab-a2-276', 'collegial', 'collegial', 'noun', 'a2', 'a2-general', 'Voorbeeld: collegial in context.', 'Example: collegial in context.', { article: 'het' }),
  buildVocab('vocab-a2-277', 'team', 'team', 'noun', 'a2', 'a2-general', 'Voorbeeld: team in context.', 'Example: team in context.', { article: 'het' }),
  buildVocab('vocab-a2-278', 'klant', 'customer', 'noun', 'a2', 'a2-general', 'Voorbeeld: klant in context.', 'Example: customer in context.', { article: 'het' }),
  buildVocab('vocab-a2-279', 'service', 'service', 'noun', 'a2', 'a2-general', 'Voorbeeld: service in context.', 'Example: service in context.', { article: 'de' }),
  buildVocab('vocab-a2-280', 'klacht', 'complaint', 'noun', 'a2', 'a2-general', 'Voorbeeld: klacht in context.', 'Example: complaint in context.', { article: 'het' }),
  buildVocab('vocab-a2-281', 'opluchting', 'relief', 'noun', 'a2', 'a2-general', 'Voorbeeld: opluchting in context.', 'Example: relief in context.', { article: 'het' }),
  buildVocab('vocab-a2-282', 'jaloezie', 'jealousy', 'noun', 'a2', 'a2-general', 'Voorbeeld: jaloezie in context.', 'Example: jealousy in context.', { article: 'de' }),
  buildVocab('vocab-a2-283', 'vertrouwen', 'trust', 'noun', 'a2', 'a2-general', 'Voorbeeld: vertrouwen in context.', 'Example: trust in context.', { article: 'het' }),
  buildVocab('vocab-a2-284', 'twijfel', 'doubt', 'noun', 'a2', 'a2-general', 'Voorbeeld: twijfel in context.', 'Example: doubt in context.', { article: 'het' }),
  buildVocab('vocab-a2-285', 'cultureel', 'cultural', 'noun', 'a2', 'a2-general', 'Voorbeeld: cultureel in context.', 'Example: cultural in context.', { article: 'het' }),
  buildVocab('vocab-a2-286', 'traditie', 'tradition', 'noun', 'a2', 'a2-general', 'Voorbeeld: traditie in context.', 'Example: tradition in context.', { article: 'de' }),
  buildVocab('vocab-a2-287', 'gewoonte', 'habit', 'noun', 'a2', 'a2-general', 'Voorbeeld: gewoonte in context.', 'Example: habit in context.', { article: 'de' }),
  buildVocab('vocab-a2-288', 'uitnodigen', 'to invite', 'verb', 'a2', 'a2-general', 'Voorbeeld: uitnodigen in context.', 'Example: to invite in context.'),
  buildVocab('vocab-a2-289', 'afwijzen', 'to decline', 'verb', 'a2', 'a2-general', 'Voorbeeld: afwijzen in context.', 'Example: to decline in context.'),
  buildVocab('vocab-a2-290', 'bevestigen', 'to confirm', 'verb', 'a2', 'a2-general', 'Voorbeeld: bevestigen in context.', 'Example: to confirm in context.'),
  buildVocab('vocab-a2-291', 'reserveren', 'to book', 'verb', 'a2', 'a2-general', 'Voorbeeld: reserveren in context.', 'Example: to book in context.'),
  buildVocab('vocab-a2-292', 'annuleren', 'to cancel', 'verb', 'a2', 'a2-general', 'Voorbeeld: annuleren in context.', 'Example: to cancel in context.'),
  buildVocab('vocab-a2-293', 'inchecken', 'to check in', 'verb', 'a2', 'a2-general', 'Voorbeeld: inchecken in context.', 'Example: to check in in context.'),
  buildVocab('vocab-a2-294', 'uitchecken', 'to check out', 'verb', 'a2', 'a2-general', 'Voorbeeld: uitchecken in context.', 'Example: to check out in context.'),
  buildVocab('vocab-a2-295', 'douane', 'customs', 'noun', 'a2', 'a2-general', 'Voorbeeld: douane in context.', 'Example: customs in context.', { article: 'de' }),
  buildVocab('vocab-a2-296', 'bagage', 'luggage', 'noun', 'a2', 'a2-general', 'Voorbeeld: bagage in context.', 'Example: luggage in context.', { article: 'de' }),
  buildVocab('vocab-a2-297', 'vertrouwd', 'familiar', 'noun', 'a2', 'a2-general', 'Voorbeeld: vertrouwd in context.', 'Example: familiar in context.', { article: 'het' }),
  buildVocab('vocab-a2-298', 'onbekend', 'unfamiliar', 'noun', 'a2', 'a2-general', 'Voorbeeld: onbekend in context.', 'Example: unfamiliar in context.', { article: 'het' }),
  buildVocab('vocab-a2-299', 'missen', 'to miss', 'verb', 'a2', 'a2-general', 'Voorbeeld: missen in context.', 'Example: to miss in context.'),
  buildVocab('vocab-a2-300', 'genieten', 'to enjoy', 'verb', 'a2', 'a2-general', 'Voorbeeld: genieten in context.', 'Example: to enjoy in context.'),
  buildVocab('vocab-a2-301', 'spijt', 'regret', 'noun', 'a2', 'a2-general', 'Voorbeeld: spijt in context.', 'Example: regret in context.', { article: 'het' }),
  buildVocab('vocab-a2-302', 'excuseren', 'to apologize', 'verb', 'a2', 'a2-general', 'Voorbeeld: excuseren in context.', 'Example: to apologize in context.'),
  buildVocab('vocab-a2-303', 'verontschuldigen', 'to apologize', 'verb', 'a2', 'a2-general', 'Voorbeeld: verontschuldigen in context.', 'Example: to apologize in context.'),
  buildVocab('vocab-a2-304', 'doorgeven', 'to pass on', 'verb', 'a2', 'a2-general', 'Voorbeeld: doorgeven in context.', 'Example: to pass on in context.'),
  buildVocab('vocab-a2-305', 'doorsturen', 'to forward', 'verb', 'a2', 'a2-general', 'Voorbeeld: doorsturen in context.', 'Example: to forward in context.'),
  buildVocab('vocab-a2-306', 'bijlage', 'attachment', 'noun', 'a2', 'a2-general', 'Voorbeeld: bijlage in context.', 'Example: attachment in context.', { article: 'de' }),
  buildVocab('vocab-a2-307', 'onderwerp', 'subject', 'noun', 'a2', 'a2-general', 'Voorbeeld: onderwerp in context.', 'Example: subject in context.', { article: 'het' }),
  buildVocab('vocab-a2-308', 'groet', 'greeting', 'noun', 'a2', 'a2-general', 'Voorbeeld: groet in context.', 'Example: greeting in context.', { article: 'het' }),
  buildVocab('vocab-a2-309', 'handtekening', 'signature', 'noun', 'a2', 'a2-general', 'Voorbeeld: handtekening in context.', 'Example: signature in context.', { article: 'het' }),
  buildVocab('vocab-a2-310', 'formulier', 'form', 'noun', 'a2', 'a2-general', 'Voorbeeld: formulier in context.', 'Example: form in context.', { article: 'het' }),
  buildVocab('vocab-a2-311', 'identiteitsbewijs', 'ID', 'noun', 'a2', 'a2-general', 'Voorbeeld: identiteitsbewijs in context.', 'Example: ID in context.', { article: 'het' }),
  buildVocab('vocab-a2-312', 'inschrijven', 'to register', 'verb', 'a2', 'a2-general', 'Voorbeeld: inschrijven in context.', 'Example: to register in context.'),
  buildVocab('vocab-a2-313', 'afmelden', 'to deregister', 'verb', 'a2', 'a2-general', 'Voorbeeld: afmelden in context.', 'Example: to deregister in context.'),
  buildVocab('vocab-a2-314', 'belasting', 'tax', 'noun', 'a2', 'a2-general', 'Voorbeeld: belasting in context.', 'Example: tax in context.', { article: 'het' }),
  buildVocab('vocab-a2-315', 'subsidie', 'subsidy', 'noun', 'a2', 'a2-general', 'Voorbeeld: subsidie in context.', 'Example: subsidy in context.', { article: 'de' }),
  buildVocab('vocab-a2-316', 'vergunning', 'permit', 'noun', 'a2', 'a2-general', 'Voorbeeld: vergunning in context.', 'Example: permit in context.', { article: 'het' }),
  buildVocab('vocab-a2-317', 'melding', 'report', 'noun', 'a2', 'a2-general', 'Voorbeeld: melding in context.', 'Example: report in context.', { article: 'het' }),
  buildVocab('vocab-a2-318', 'reparatie', 'repair', 'noun', 'a2', 'a2-general', 'Voorbeeld: reparatie in context.', 'Example: repair in context.', { article: 'de' }),
  buildVocab('vocab-a2-319', 'offerte', 'quote', 'noun', 'a2', 'a2-general', 'Voorbeeld: offerte in context.', 'Example: quote in context.', { article: 'de' }),
  buildVocab('vocab-a2-320', 'akkoord', 'agreement', 'noun', 'a2', 'a2-general', 'Voorbeeld: akkoord in context.', 'Example: agreement in context.', { article: 'het' }),
];
