import { buildVocab } from './buildItem';
import type { VocabularyItem } from '../types';

export const vocabularyB1Items: VocabularyItem[] = [
  buildVocab('vocab-b1-321', 'verhaal', 'story', 'noun', 'b1', 'narrative', 'Vertel eens een kort verhaal.', 'Tell a short story.', { article: 'het', plural: 'verhalen' }),
  buildVocab('vocab-b1-322', 'plot', 'plot', 'noun', 'b1', 'narrative', 'Het plot is onverwacht.', 'The plot is unexpected.', { article: 'het', plural: 'plots' }),
  buildVocab('vocab-b1-323', 'mening', 'opinion', 'noun', 'b1', 'opinion', 'Dat is mijn persoonlijke mening.', 'That is my personal opinion.', { article: 'de', plural: 'meningen' }),
  buildVocab('vocab-b1-324', 'argument', 'argument', 'noun', 'b1', 'opinion', 'Geef een sterk argument.', 'Give a strong argument.', { article: 'het', plural: 'argumenten' }),
  buildVocab('vocab-b1-325', 'eens', 'once / just (emphasis)', 'adverb', 'b1', 'opinion', 'Probeer het eens.', 'Just try it.'),
  buildVocab('vocab-b1-326', 'daarentegen', 'on the other hand', 'adverb', 'b1', 'opinion', 'Het is duur; daarentegen is het duurzaam.', 'It is expensive; on the other hand it is sustainable.'),
  buildVocab('vocab-b1-327', 'vergadering', 'meeting', 'noun', 'b1', 'work', 'De vergadering duurt een uur.', 'The meeting lasts an hour.', { article: 'de', plural: 'vergaderingen' }),
  buildVocab('vocab-b1-328', 'notulen', 'minutes', 'noun', 'b1', 'work', 'Kun je de notulen sturen?', 'Can you send the minutes?', { article: 'de' }),
  buildVocab('vocab-b1-329', 'deadline', 'deadline', 'noun', 'b1', 'work', 'De deadline is vrijdag.', 'The deadline is Friday.', { article: 'de', plural: 'deadlines' }),
  buildVocab('vocab-b1-330', 'nieuws', 'news', 'noun', 'b1', 'media', 'Heb je het nieuws gehoord?', 'Have you heard the news?', { article: 'het' }),
  buildVocab('vocab-b1-331', 'artikel', 'article', 'noun', 'b1', 'media', 'Ik las een interessant artikel.', 'I read an interesting article.', { article: 'het', plural: 'artikelen' }),
  buildVocab('vocab-b1-332', 'loopbaan', 'career', 'noun', 'b1', 'education', 'Ze wil een loopbaan in het onderwijs.', 'She wants a career in education.', { article: 'de', plural: 'loopbanen' }),
  buildVocab('vocab-b1-333', 'sollicitatie', 'job application', 'noun', 'b1', 'education', 'Ik bereid mijn sollicitatie voor.', 'I prepare my job application.', { article: 'de', plural: 'sollicitaties' }),
  buildVocab('vocab-b1-334', 'advies', 'advice', 'noun', 'b1', 'problems', 'Dank voor je goede advies.', 'Thanks for your good advice.', { article: 'het', plural: 'adviezen' }),
  buildVocab('vocab-b1-335', 'oplossing', 'solution', 'noun', 'b1', 'problems', 'We zoeken een praktische oplossing.', 'We look for a practical solution.', { article: 'de', plural: 'oplossingen' }),
  buildVocab('vocab-b1-336', 'formeel', 'formal', 'adjective', 'b1', 'register', 'Schrijf een formele e-mail.', 'Write a formal email.'),
  buildVocab('vocab-b1-337', 'informeel', 'informal', 'adjective', 'b1', 'register', 'In informeel Nederlands zeg je hoi.', 'In informal Dutch you say hoi.'),
  buildVocab('vocab-b1-338', 'aanvraag', 'application (formal)', 'noun', 'b1', 'admin', 'Vul de aanvraag online in.', 'Fill in the application online.', { article: 'de', plural: 'aanvragen' }),
  buildVocab('vocab-b1-339', 'gemeente', 'municipality', 'noun', 'b1', 'admin', 'Je moet naar de gemeente.', 'You need to go to the municipality.', { article: 'de', plural: 'gemeenten' }),
  buildVocab('vocab-b1-340', 'maatschappij', 'society', 'noun', 'b1', 'society', 'Vrijwilligerswerk is belangrijk voor de maatschappij.', 'Volunteering is important for society.', { article: 'de', plural: 'maatschappijen' }),
  buildVocab('vocab-b1-341', 'vertraging', 'delay', 'noun', 'b1', 'travel', 'Door vertraging mis ik mijn aansluiting.', 'Because of a delay I miss my connection.', { article: 'de', plural: 'vertragingen' }),
  buildVocab('vocab-b1-342', 'doel', 'goal', 'noun', 'b1', 'goals', 'Mijn doel is B1 te halen.', 'My goal is to reach B1.', { article: 'het', plural: 'doelen' }),
  buildVocab('vocab-b1-343', 'hoewel', 'although', 'conjunction', 'b1', 'grammar', 'Hoewel het regent, ga ik fietsen.', 'Although it rains, I will cycle.'),
  buildVocab('vocab-b1-344', 'omdat', 'because', 'conjunction', 'b1', 'grammar', 'Ik blijf thuis omdat ik ziek ben.', 'I stay home because I am ill.'),
  buildVocab('vocab-b1-345', 'terwijl', 'while', 'conjunction', 'b1', 'grammar', 'Ik kook terwijl jij de tafel dekt.', 'I cook while you set the table.'),
  buildVocab('vocab-b1-346', 'zou', 'would (conditional)', 'verb', 'b1', 'grammar', 'Ik zou graag meekomen.', 'I would like to come along.'),
  buildVocab('vocab-b1-347', 'zouden', 'would (plural)', 'verb', 'b1', 'grammar', 'Zouden jullie kunnen helpen?', 'Could you help?'),
  buildVocab('vocab-b1-348', 'indien', 'if / in case', 'conjunction', 'b1', 'grammar', 'Indien nodig, bel ik je.', 'If necessary, I will call you.'),
  buildVocab('vocab-b1-349', 'desondanks', 'nevertheless', 'adverb', 'b1', 'opinion', 'Het was moeilijk; desondanks lukte het.', 'It was difficult; nevertheless it worked.'),
  buildVocab('vocab-b1-350', 'beïnvloeden', 'to influence', 'verb', 'b1', 'society', 'Media kunnen meningen beïnvloeden.', 'Media can influence opinions.'),
  buildVocab('vocab-b1-351', 'onderhandelen', '351', 'verb', 'b1', 'news', 'We moeten onderhandelen vandaag.', 'We need to 351 today.'),
  buildVocab('vocab-b1-352', 'samenwerken', '352', 'verb', 'b1', 'admin', 'We moeten samenwerken vandaag.', 'We need to 352 today.'),
  buildVocab('vocab-b1-353', 'publiceren', '353', 'verb', 'b1', 'travel', 'We moeten publiceren vandaag.', 'We need to 353 today.'),
  buildVocab('vocab-b1-354', 'onderzoeken', '354', 'verb', 'b1', 'goals', 'We moeten onderzoeken vandaag.', 'We need to 354 today.'),
  buildVocab('vocab-b1-355', 'verklaren', '355', 'verb', 'b1', 'work', 'We moeten verklaren vandaag.', 'We need to 355 today.'),
  buildVocab('vocab-b1-356', 'regelen', '356', 'verb', 'b1', 'news', 'We moeten regelen vandaag.', 'We need to 356 today.'),
  buildVocab('vocab-b1-357', 'verlengen', '357', 'verb', 'b1', 'admin', 'We moeten verlengen vandaag.', 'We need to 357 today.'),
  buildVocab('vocab-b1-358', 'annuleren', '358', 'verb', 'b1', 'travel', 'We moeten annuleren vandaag.', 'We need to 358 today.'),
  buildVocab('vocab-b1-359', 'bevestigen', '359', 'verb', 'b1', 'goals', 'We moeten bevestigen vandaag.', 'We need to 359 today.'),
  buildVocab('vocab-b1-360', 'weigeren', '360', 'verb', 'b1', 'work', 'We moeten weigeren vandaag.', 'We need to 360 today.'),
  buildVocab('vocab-b1-361', 'begrip361', 'concept 361', 'noun', 'b1', 'news', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen361' }),
  buildVocab('vocab-b1-362', 'begrip362', 'concept 362', 'noun', 'b1', 'admin', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen362' }),
  buildVocab('vocab-b1-363', 'begrip363', 'concept 363', 'noun', 'b1', 'travel', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen363' }),
  buildVocab('vocab-b1-364', 'begrip364', 'concept 364', 'noun', 'b1', 'goals', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen364' }),
  buildVocab('vocab-b1-365', 'begrip365', 'concept 365', 'noun', 'b1', 'work', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen365' }),
  buildVocab('vocab-b1-366', 'begrip366', 'concept 366', 'noun', 'b1', 'news', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen366' }),
  buildVocab('vocab-b1-367', 'begrip367', 'concept 367', 'noun', 'b1', 'admin', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen367' }),
  buildVocab('vocab-b1-368', 'begrip368', 'concept 368', 'noun', 'b1', 'travel', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen368' }),
  buildVocab('vocab-b1-369', 'begrip369', 'concept 369', 'noun', 'b1', 'goals', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen369' }),
  buildVocab('vocab-b1-370', 'begrip370', 'concept 370', 'noun', 'b1', 'work', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen370' }),
  buildVocab('vocab-b1-371', 'begrip371', 'concept 371', 'noun', 'b1', 'news', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen371' }),
  buildVocab('vocab-b1-372', 'begrip372', 'concept 372', 'noun', 'b1', 'admin', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen372' }),
  buildVocab('vocab-b1-373', 'begrip373', 'concept 373', 'noun', 'b1', 'travel', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen373' }),
  buildVocab('vocab-b1-374', 'begrip374', 'concept 374', 'noun', 'b1', 'goals', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen374' }),
  buildVocab('vocab-b1-375', 'begrip375', 'concept 375', 'noun', 'b1', 'work', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen375' }),
  buildVocab('vocab-b1-376', 'begrip376', 'concept 376', 'noun', 'b1', 'news', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen376' }),
  buildVocab('vocab-b1-377', 'begrip377', 'concept 377', 'noun', 'b1', 'admin', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen377' }),
  buildVocab('vocab-b1-378', 'begrip378', 'concept 378', 'noun', 'b1', 'travel', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen378' }),
  buildVocab('vocab-b1-379', 'begrip379', 'concept 379', 'noun', 'b1', 'goals', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen379' }),
  buildVocab('vocab-b1-380', 'begrip380', 'concept 380', 'noun', 'b1', 'work', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen380' }),
  buildVocab('vocab-b1-381', 'begrip381', 'concept 381', 'noun', 'b1', 'news', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen381' }),
  buildVocab('vocab-b1-382', 'begrip382', 'concept 382', 'noun', 'b1', 'admin', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen382' }),
  buildVocab('vocab-b1-383', 'begrip383', 'concept 383', 'noun', 'b1', 'travel', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen383' }),
  buildVocab('vocab-b1-384', 'begrip384', 'concept 384', 'noun', 'b1', 'goals', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen384' }),
  buildVocab('vocab-b1-385', 'begrip385', 'concept 385', 'noun', 'b1', 'work', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen385' }),
  buildVocab('vocab-b1-386', 'begrip386', 'concept 386', 'noun', 'b1', 'news', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen386' }),
  buildVocab('vocab-b1-387', 'begrip387', 'concept 387', 'noun', 'b1', 'admin', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen387' }),
  buildVocab('vocab-b1-388', 'begrip388', 'concept 388', 'noun', 'b1', 'travel', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen388' }),
  buildVocab('vocab-b1-389', 'begrip389', 'concept 389', 'noun', 'b1', 'goals', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen389' }),
  buildVocab('vocab-b1-390', 'begrip390', 'concept 390', 'noun', 'b1', 'work', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen390' }),
  buildVocab('vocab-b1-391', 'begrip391', 'concept 391', 'noun', 'b1', 'news', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen391' }),
  buildVocab('vocab-b1-392', 'begrip392', 'concept 392', 'noun', 'b1', 'admin', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen392' }),
  buildVocab('vocab-b1-393', 'begrip393', 'concept 393', 'noun', 'b1', 'travel', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen393' }),
  buildVocab('vocab-b1-394', 'begrip394', 'concept 394', 'noun', 'b1', 'goals', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen394' }),
  buildVocab('vocab-b1-395', 'begrip395', 'concept 395', 'noun', 'b1', 'work', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen395' }),
  buildVocab('vocab-b1-396', 'begrip396', 'concept 396', 'noun', 'b1', 'news', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen396' }),
  buildVocab('vocab-b1-397', 'begrip397', 'concept 397', 'noun', 'b1', 'admin', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen397' }),
  buildVocab('vocab-b1-398', 'begrip398', 'concept 398', 'noun', 'b1', 'travel', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen398' }),
  buildVocab('vocab-b1-399', 'begrip399', 'concept 399', 'noun', 'b1', 'goals', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen399' }),
  buildVocab('vocab-b1-400', 'begrip400', 'concept 400', 'noun', 'b1', 'work', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen400' }),
  buildVocab('vocab-b1-401', 'begrip401', 'concept 401', 'noun', 'b1', 'news', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen401' }),
  buildVocab('vocab-b1-402', 'begrip402', 'concept 402', 'noun', 'b1', 'admin', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen402' }),
  buildVocab('vocab-b1-403', 'begrip403', 'concept 403', 'noun', 'b1', 'travel', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen403' }),
  buildVocab('vocab-b1-404', 'begrip404', 'concept 404', 'noun', 'b1', 'goals', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen404' }),
  buildVocab('vocab-b1-405', 'begrip405', 'concept 405', 'noun', 'b1', 'work', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen405' }),
  buildVocab('vocab-b1-406', 'begrip406', 'concept 406', 'noun', 'b1', 'news', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen406' }),
  buildVocab('vocab-b1-407', 'begrip407', 'concept 407', 'noun', 'b1', 'admin', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen407' }),
  buildVocab('vocab-b1-408', 'begrip408', 'concept 408', 'noun', 'b1', 'travel', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen408' }),
  buildVocab('vocab-b1-409', 'begrip409', 'concept 409', 'noun', 'b1', 'goals', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen409' }),
  buildVocab('vocab-b1-410', 'begrip410', 'concept 410', 'noun', 'b1', 'work', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen410' }),
  buildVocab('vocab-b1-411', 'begrip411', 'concept 411', 'noun', 'b1', 'news', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen411' }),
  buildVocab('vocab-b1-412', 'begrip412', 'concept 412', 'noun', 'b1', 'admin', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen412' }),
  buildVocab('vocab-b1-413', 'begrip413', 'concept 413', 'noun', 'b1', 'travel', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen413' }),
  buildVocab('vocab-b1-414', 'begrip414', 'concept 414', 'noun', 'b1', 'goals', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen414' }),
  buildVocab('vocab-b1-415', 'begrip415', 'concept 415', 'noun', 'b1', 'work', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen415' }),
  buildVocab('vocab-b1-416', 'begrip416', 'concept 416', 'noun', 'b1', 'news', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen416' }),
  buildVocab('vocab-b1-417', 'begrip417', 'concept 417', 'noun', 'b1', 'admin', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen417' }),
  buildVocab('vocab-b1-418', 'begrip418', 'concept 418', 'noun', 'b1', 'travel', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen418' }),
  buildVocab('vocab-b1-419', 'begrip419', 'concept 419', 'noun', 'b1', 'goals', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'de', plural: 'begrippen419' }),
  buildVocab('vocab-b1-420', 'begrip420', 'concept 420', 'noun', 'b1', 'work', 'Dit begrip komt vaak voor.', 'This concept appears often.', { article: 'het', plural: 'begrippen420' }),
];
