import { buildVocab } from './buildItem';
import type { VocabularyItem } from '../types';

export const vocabularyB2Items: VocabularyItem[] = [
  buildVocab('vocab-b2-421', 'nuanceren', 'to nuance', 'verb', 'b2', 'argument', 'Ik wil mijn mening nuanceren.', 'I want to nuance my opinion.'),
  buildVocab('vocab-b2-422', 'standpunt', 'position / viewpoint', 'noun', 'b2', 'argument', 'Wat is jouw standpunt?', 'What is your position?', { article: 'het', plural: 'standpunten' }),
  buildVocab('vocab-b2-423', 'tegenargument', 'counter-argument', 'noun', 'b2', 'argument', 'Heb je een tegenargument?', 'Do you have a counter-argument?', { article: 'het', plural: 'tegenargumenten' }),
  buildVocab('vocab-b2-424', 'overtuigen', 'to persuade', 'verb', 'b2', 'argument', 'Zij probeert ons te overtuigen.', 'She is trying to persuade us.'),
  buildVocab('vocab-b2-425', 'relatief', 'relatively', 'adverb', 'b2', 'argument', 'Dat is relatief nieuw.', 'That is relatively new.'),
  buildVocab('vocab-b2-426', 'desalniettemin', 'nevertheless', 'adverb', 'b2', 'connectors', 'Desalniettemin ga ik door.', 'Nevertheless I continue.'),
  buildVocab('vocab-b2-427', 'hoewel', 'although', 'conjunction', 'b2', 'connectors', 'Hoewel het regent, fietsen we.', 'Although it rains, we cycle.'),
  buildVocab('vocab-b2-428', 'mits', 'provided that', 'conjunction', 'b2', 'connectors', 'Je mag gaan, mits je op tijd bent.', 'You may go, provided you are on time.'),
  buildVocab('vocab-b2-429', 'tenzij', 'unless', 'conjunction', 'b2', 'connectors', 'Ik kom, tenzij de trein uitvalt.', 'I am coming unless the train is cancelled.'),
  buildVocab('vocab-b2-430', 'enerzijds', 'on the one hand', 'adverb', 'b2', 'connectors', 'Enerzijds is het handig.', 'On the one hand it is convenient.'),
  buildVocab('vocab-b2-431', 'anderzijds', 'on the other hand', 'adverb', 'b2', 'connectors', 'Anderzijds kost het tijd.', 'On the other hand it costs time.'),
  buildVocab('vocab-b2-432', 'hypothetisch', 'hypothetical', 'adjective', 'b2', 'hypothesis', 'Dit is een hypothetische situatie.', 'This is a hypothetical situation.'),
  buildVocab('vocab-b2-433', 'zou hebben', 'would have (conditional perfect)', 'phrase', 'b2', 'hypothesis', 'Ik zou het hebben gedaan.', 'I would have done it.'),
  buildVocab('vocab-b2-434', 'onderhandelen', 'to negotiate', 'verb', 'b2', 'work', 'We onderhandelen over de voorwaarden.', 'We are negotiating the terms.'),
  buildVocab('vocab-b2-435', 'voorwaarde', 'condition', 'noun', 'b2', 'work', 'Dat is een harde voorwaarde.', 'That is a hard condition.', { article: 'de', plural: 'voorwaarden' }),
  buildVocab('vocab-b2-436', 'compromis', 'compromise', 'noun', 'b2', 'work', 'Laten we een compromis zoeken.', 'Let us look for a compromise.', { article: 'het', plural: 'compromissen' }),
  buildVocab('vocab-b2-437', 'deadline', 'deadline', 'noun', 'b2', 'work', 'De deadline is vrijdag.', 'The deadline is Friday.', { article: 'de', plural: 'deadlines' }),
  buildVocab('vocab-b2-438', 'vergaderstukken', 'meeting documents', 'noun', 'b2', 'work', 'Heb je de vergaderstukken gelezen?', 'Have you read the meeting documents?', { article: 'de' }),
  buildVocab('vocab-b2-439', 'besluitvorming', 'decision-making', 'noun', 'b2', 'work', 'De besluitvorming duurt lang.', 'Decision-making takes a long time.', { article: 'de' }),
  buildVocab('vocab-b2-440', 'kritisch', 'critical', 'adjective', 'b2', 'media', 'Lees kritisch.', 'Read critically.'),
  buildVocab('vocab-b2-441', 'bron', 'source', 'noun', 'b2', 'media', 'Controleer je bronnen.', 'Check your sources.', { article: 'de', plural: 'bronnen' }),
  buildVocab('vocab-b2-442', 'berichtgeving', 'news coverage', 'noun', 'b2', 'media', 'De berichtgeving is eenzijdig.', 'The coverage is one-sided.', { article: 'de' }),
  buildVocab('vocab-b2-443', 'desinformatie', 'disinformation', 'noun', 'b2', 'media', 'Desinformatie verspreidt zich snel.', 'Disinformation spreads quickly.', { article: 'de' }),
  buildVocab('vocab-b2-444', 'nuance', 'nuance', 'noun', 'b2', 'media', 'Er mist nuance in het artikel.', 'Nuance is missing in the article.', { article: 'de', plural: 'nuances' }),
  buildVocab('vocab-b2-445', 'abstract', 'abstract', 'adjective', 'b2', 'culture', 'Dit is een abstract begrip.', 'This is an abstract concept.'),
  buildVocab('vocab-b2-446', 'interpretatie', 'interpretation', 'noun', 'b2', 'culture', 'Elke interpretatie is anders.', 'Every interpretation is different.', { article: 'de', plural: 'interpretaties' }),
  buildVocab('vocab-b2-447', 'tentoonstelling', 'exhibition', 'noun', 'b2', 'culture', 'De tentoonstelling is indrukwekkend.', 'The exhibition is impressive.', { article: 'de', plural: 'tentoonstellingen' }),
  buildVocab('vocab-b2-448', 'recensie', 'review', 'noun', 'b2', 'culture', 'Ik schreef een recensie.', 'I wrote a review.', { article: 'de', plural: 'recensies' }),
  buildVocab('vocab-b2-449', 'literair', 'literary', 'adjective', 'b2', 'culture', 'Een literaire tekst vraagt aandacht.', 'A literary text requires attention.'),
  buildVocab('vocab-b2-450', 'perspectief', 'perspective', 'noun', 'b2', 'narrative', 'Vanuit haar perspectief is het anders.', 'From her perspective it is different.', { article: 'het', plural: 'perspectieven' }),
  buildVocab('vocab-b2-451', 'flashback', 'flashback', 'noun', 'b2', 'narrative', 'Het verhaal begint met een flashback.', 'The story starts with a flashback.', { article: 'de', plural: 'flashbacks' }),
  buildVocab('vocab-b2-452', 'spanningsboog', 'narrative arc', 'noun', 'b2', 'narrative', 'De spanningsboog is sterk.', 'The narrative arc is strong.', { article: 'de', plural: 'spanningsbogen' }),
  buildVocab('vocab-b2-453', 'impliciet', 'implicit', 'adjective', 'b2', 'narrative', 'De kritiek is impliciet.', 'The criticism is implicit.'),
  buildVocab('vocab-b2-454', 'expliciet', 'explicit', 'adjective', 'b2', 'narrative', 'Wees expliciet over je doelen.', 'Be explicit about your goals.'),
  buildVocab('vocab-b2-455', 'studiebelasting', 'study load', 'noun', 'b2', 'study', 'De studiebelasting is hoog.', 'The study load is high.', { article: 'de' }),
  buildVocab('vocab-b2-456', 'onderzoeksvraag', 'research question', 'noun', 'b2', 'study', 'Formuleer een onderzoeksvraag.', 'Formulate a research question.', { article: 'de', plural: 'onderzoeksvragen' }),
  buildVocab('vocab-b2-457', 'bronvermelding', 'citation', 'noun', 'b2', 'study', 'Vergeet de bronvermelding niet.', 'Do not forget the citation.', { article: 'de', plural: 'bronvermeldingen' }),
  buildVocab('vocab-b2-458', 'samenvatten', 'to summarise', 'verb', 'b2', 'study', 'Kun je de tekst samenvatten?', 'Can you summarise the text?'),
  buildVocab('vocab-b2-459', 'parafraseren', 'to paraphrase', 'verb', 'b2', 'study', 'Parafraseer de zin in eigen woorden.', 'Paraphrase the sentence in your own words.'),
  buildVocab('vocab-b2-460', 'duurzaamheid', 'sustainability', 'noun', 'b2', 'society', 'Duurzaamheid staat centraal.', 'Sustainability is central.', { article: 'de' }),
  buildVocab('vocab-b2-461', 'ongelijkheid', 'inequality', 'noun', 'b2', 'society', 'Ongelijkheid blijft een probleem.', 'Inequality remains a problem.', { article: 'de' }),
  buildVocab('vocab-b2-462', 'participatie', 'participation', 'noun', 'b2', 'society', 'Participatie van burgers is belangrijk.', 'Citizen participation is important.', { article: 'de' }),
  buildVocab('vocab-b2-463', 'beleid', 'policy', 'noun', 'b2', 'society', 'Het beleid verandert volgend jaar.', 'The policy changes next year.', { article: 'het' }),
  buildVocab('vocab-b2-464', 'maatschappelijk', 'societal', 'adjective', 'b2', 'society', 'Dit is een maatschappelijk debat.', 'This is a societal debate.'),
  buildVocab('vocab-b2-465', 'vooruitzicht', 'prospect', 'noun', 'b2', 'future', 'De vooruitzichten zijn goed.', 'The prospects are good.', { article: 'het', plural: 'vooruitzichten' }),
  buildVocab('vocab-b2-466', 'ambitie', 'ambition', 'noun', 'b2', 'future', 'Zij heeft grote ambities.', 'She has big ambitions.', { article: 'de', plural: 'ambities' }),
  buildVocab('vocab-b2-467', 'scenario', 'scenario', 'noun', 'b2', 'future', 'In dit scenario werken we thuis.', 'In this scenario we work from home.', { article: 'het', plural: 'scenario\'s' }),
  buildVocab('vocab-b2-468', 'waarschijnlijk', 'probably / likely', 'adverb', 'b2', 'future', 'Dat is waarschijnlijk waar.', 'That is probably true.'),
  buildVocab('vocab-b2-469', 'onwaarschijnlijk', 'unlikely', 'adjective', 'b2', 'future', 'Het is onwaarschijnlijk dat hij komt.', 'It is unlikely that he is coming.'),
  buildVocab('vocab-b2-470', 'uiteindelijk', 'ultimately / eventually', 'adverb', 'b2', 'connectors', 'Uiteindelijk koos ik voor rust.', 'Ultimately I chose rest.'),
  buildVocab('vocab-b2-471', 'desondanks', 'despite that', 'adverb', 'b2', 'connectors', 'Desondanks bleef hij vriendelijk.', 'Despite that he stayed friendly.'),
  buildVocab('vocab-b2-472', 'bovendien', 'moreover', 'adverb', 'b2', 'connectors', 'Bovendien is het goedkoper.', 'Moreover it is cheaper.'),
  buildVocab('vocab-b2-473', 'daarentegen', 'by contrast', 'adverb', 'b2', 'connectors', 'Daarentegen werkt plan B beter.', 'By contrast plan B works better.'),
  buildVocab('vocab-b2-474', 'consequentie', 'consequence', 'noun', 'b2', 'argument', 'Denk aan de consequenties.', 'Think about the consequences.', { article: 'de', plural: 'consequenties' }),
  buildVocab('vocab-b2-475', 'aanname', 'assumption', 'noun', 'b2', 'argument', 'Die aanname is twijfelachtig.', 'That assumption is doubtful.', { article: 'de', plural: 'aannames' }),
  buildVocab('vocab-b2-476', 'bewijs', 'evidence', 'noun', 'b2', 'argument', 'Waar is het bewijs?', 'Where is the evidence?', { article: 'het' }),
  buildVocab('vocab-b2-477', 'reflecteren', 'to reflect', 'verb', 'b2', 'study', 'Reflecteer op je leerproces.', 'Reflect on your learning process.'),
  buildVocab('vocab-b2-478', 'feedback', 'feedback', 'noun', 'b2', 'work', 'Ik waardeer constructieve feedback.', 'I appreciate constructive feedback.', { article: 'de' }),
  buildVocab('vocab-b2-479', 'prioriteit', 'priority', 'noun', 'b2', 'work', 'Wat is de prioriteit vandaag?', 'What is the priority today?', { article: 'de', plural: 'prioriteiten' }),
  buildVocab('vocab-b2-480', 'stakeholders', 'stakeholders', 'noun', 'b2', 'work', 'We betrekken alle stakeholders.', 'We involve all stakeholders.', { article: 'de' }),
];
