import { buildVocab } from './buildItem';
import type { VocabularyItem } from '../types';

export const vocabularyPreA1Items: VocabularyItem[] = [
  buildVocab('vocab-pre-a1-001', 'letter', 'letter', 'noun', 'pre-a1', 'alphabet', 'De letter B is mooi rond.', 'The letter B is nicely round.', { article: 'de', plural: 'letters' }),
  buildVocab('vocab-pre-a1-002', 'alfabet', 'alphabet', 'noun', 'pre-a1', 'alphabet', 'Ik oefen het alfabet elke dag.', 'I practise the alphabet every day.', { article: 'het' }),
  buildVocab('vocab-pre-a1-003', 'spellen', 'to spell', 'verb', 'pre-a1', 'alphabet', 'Spell je achternaam, alsjeblieft.', 'Please spell your surname.'),
  buildVocab('vocab-pre-a1-004', 'voornaam', 'first name', 'noun', 'pre-a1', 'alphabet', 'Mijn voornaam is Sam.', 'My first name is Sam.', { article: 'de', plural: 'voornamen' }),
  buildVocab('vocab-pre-a1-005', 'achternaam', 'surname', 'noun', 'pre-a1', 'alphabet', 'Wat is je achternaam?', 'What is your surname?', { article: 'de', plural: 'achternamen' }),
  buildVocab('vocab-pre-a1-006', 'hoofdletter', 'capital letter', 'noun', 'pre-a1', 'alphabet', 'Amsterdam schrijf je met een hoofdletter.', 'You write Amsterdam with a capital letter.', { article: 'de', plural: 'hoofdletters' }),
  buildVocab('vocab-pre-a1-007', 'klinker', 'vowel', 'noun', 'pre-a1', 'pronunciation', 'I en e zijn klinkers.', 'I and e are vowels.', { article: 'de', plural: 'klinkers' }),
  buildVocab('vocab-pre-a1-008', 'medeklinker', 'consonant', 'noun', 'pre-a1', 'pronunciation', 'T is een medeklinker.', 'T is a consonant.', { article: 'de', plural: 'medeklinkers' }),
  buildVocab('vocab-pre-a1-009', 'g', 'g sound', 'noun', 'pre-a1', 'pronunciation', 'In gracht hoor je een harde g.', 'In gracht you hear a hard g.', { notes: 'Hard g in het midden van woorden.' }),
  buildVocab('vocab-pre-a1-010', 'ui', 'ui diphthong', 'noun', 'pre-a1', 'pronunciation', 'Huis rijmt bij muis.', 'House rhymes with mouse.', { notes: 'Say it like "ow" + short "i".' }),
  buildVocab('vocab-pre-a1-011', 'eu', 'eu sound', 'noun', 'pre-a1', 'pronunciation', 'Neus en zeug klinken op eu.', 'Nose and sow sound like eu.'),
  buildVocab('vocab-pre-a1-012', 'ij', 'ij diphthong', 'noun', 'pre-a1', 'pronunciation', 'Wij eten rijst.', 'We eat rice.', { notes: 'Similar to English "eye".' }),
  buildVocab('vocab-pre-a1-013', 'sch', 'sch cluster', 'noun', 'pre-a1', 'pronunciation', 'School begint om half negen.', 'School starts at half past eight.'),
  buildVocab('vocab-pre-a1-014', 'hallo', 'hello', 'interjection', 'pre-a1', 'greetings', 'Hallo, ik ben nieuw hier.', 'Hello, I am new here.'),
  buildVocab('vocab-pre-a1-015', 'hoi', 'hi', 'interjection', 'pre-a1', 'greetings', 'Hoi, alles goed?', 'Hi, everything okay?'),
  buildVocab('vocab-pre-a1-016', 'dag', 'bye', 'interjection', 'pre-a1', 'greetings', 'Dag, tot ziens!', 'Bye, see you!'),
  buildVocab('vocab-pre-a1-017', 'doei', 'bye (informal)', 'interjection', 'pre-a1', 'greetings', 'Doei, tot vanmiddag!', 'Bye, see you this afternoon!'),
  buildVocab('vocab-pre-a1-018', 'goedemorgen', 'good morning', 'phrase', 'pre-a1', 'greetings', 'Goedemorgen, welkom in de les.', 'Good morning, welcome to the lesson.'),
  buildVocab('vocab-pre-a1-019', 'goedemiddag', 'good afternoon', 'phrase', 'pre-a1', 'greetings', 'Goedemiddag, neem plaats.', 'Good afternoon, take a seat.'),
  buildVocab('vocab-pre-a1-020', 'goedenavond', 'good evening', 'phrase', 'pre-a1', 'greetings', 'Goedenavond, fijn dat je er bent.', 'Good evening, glad you are here.'),
  buildVocab('vocab-pre-a1-021', 'goedenacht', 'good night', 'phrase', 'pre-a1', 'greetings', 'Goedenacht en tot morgen.', 'Good night and see you tomorrow.'),
  buildVocab('vocab-pre-a1-022', 'dank je wel', 'thank you', 'phrase', 'pre-a1', 'greetings', 'Dank je wel voor het uitleggen.', 'Thank you for explaining.'),
  buildVocab('vocab-pre-a1-023', 'dank u wel', 'thank you (formal)', 'phrase', 'pre-a1', 'greetings', 'Dank u wel, mevrouw De Vries.', 'Thank you, Mrs De Vries.'),
  buildVocab('vocab-pre-a1-024', 'graag gedaan', 'you are welcome', 'phrase', 'pre-a1', 'greetings', 'Graag gedaan!', 'You are welcome!'),
  buildVocab('vocab-pre-a1-025', 'alsjeblieft', 'please / here you are', 'phrase', 'pre-a1', 'greetings', 'Twee kaartjes, alsjeblieft.', 'Two tickets, please.'),
  buildVocab('vocab-pre-a1-026', 'alstublieft', 'please (formal)', 'phrase', 'pre-a1', 'greetings', 'Mag ik de rekening, alstublieft?', 'May I have the bill, please?'),
  buildVocab('vocab-pre-a1-027', 'sorry', 'sorry', 'interjection', 'pre-a1', 'greetings', 'Sorry, ik begrijp het niet.', 'Sorry, I do not understand.'),
  buildVocab('vocab-pre-a1-028', 'pardon', 'excuse me', 'interjection', 'pre-a1', 'greetings', 'Pardon, spreekt u Engels?', 'Excuse me, do you speak English?'),
  buildVocab('vocab-pre-a1-029', 'aangenaam', 'nice to meet you', 'adjective', 'pre-a1', 'greetings', 'Aangenaam, ik heet Omar.', 'Nice to meet you, I am Omar.'),
  buildVocab('vocab-pre-a1-030', 'ik', 'I', 'pronoun', 'pre-a1', 'introduction', 'Ik kom uit België.', 'I come from Belgium.'),
  buildVocab('vocab-pre-a1-031', 'jij', 'you (informal)', 'pronoun', 'pre-a1', 'introduction', 'Jij spreekt al goed Nederlands.', 'You already speak Dutch well.'),
  buildVocab('vocab-pre-a1-032', 'u', 'you (formal)', 'pronoun', 'pre-a1', 'introduction', 'Waar woont u?', 'Where do you live?'),
  buildVocab('vocab-pre-a1-033', 'hij', 'he', 'pronoun', 'pre-a1', 'introduction', 'Hij is mijn docent.', 'He is my teacher.'),
  buildVocab('vocab-pre-a1-034', 'zij', 'she', 'pronoun', 'pre-a1', 'introduction', 'Zij woont in Utrecht.', 'She lives in Utrecht.'),
  buildVocab('vocab-pre-a1-035', 'wij', 'we', 'pronoun', 'pre-a1', 'introduction', 'Wij leren samen Nederlands.', 'We learn Dutch together.'),
  buildVocab('vocab-pre-a1-036', 'jullie', 'you (plural)', 'pronoun', 'pre-a1', 'introduction', 'Jullie zijn op tijd.', 'You are on time.'),
  buildVocab('vocab-pre-a1-037', 'zij', 'they', 'pronoun', 'pre-a1', 'introduction', 'Zij werken in Amsterdam.', 'They work in Amsterdam.'),
  buildVocab('vocab-pre-a1-038', 'heten', 'to be called', 'verb', 'pre-a1', 'introduction', 'Ik heet Nina.', 'I am called Nina.'),
  buildVocab('vocab-pre-a1-039', 'komen', 'to come', 'verb', 'pre-a1', 'introduction', 'Ik kom uit Spanje.', 'I come from Spain.'),
  buildVocab('vocab-pre-a1-040', 'wonen', 'to live', 'verb', 'pre-a1', 'introduction', 'Ik woon in Groningen.', 'I live in Groningen.'),
  buildVocab('vocab-pre-a1-041', 'nul', 'zero', 'numeral', 'pre-a1', 'numbers', 'Het is nul graden buiten.', 'It is zero degrees outside.'),
  buildVocab('vocab-pre-a1-042', 'een', 'one / a', 'numeral', 'pre-a1', 'numbers', 'Eén kopje thee, alsjeblieft.', 'One cup of tea, please.'),
  buildVocab('vocab-pre-a1-043', 'twee', 'two', 'numeral', 'pre-a1', 'numbers', 'Ik heb twee penningen.', 'I have two coins.'),
  buildVocab('vocab-pre-a1-044', 'drie', 'three', 'numeral', 'pre-a1', 'numbers', 'Drie appels in de tas.', 'Three apples in the bag.'),
  buildVocab('vocab-pre-a1-045', 'vier', 'four', 'numeral', 'pre-a1', 'numbers', 'We eten om vier uur.', 'We eat at four o clock.'),
  buildVocab('vocab-pre-a1-046', 'vijf', 'five', 'numeral', 'pre-a1', 'numbers', 'Vijf minuten wachten.', 'Wait five minutes.'),
  buildVocab('vocab-pre-a1-047', 'zes', 'six', 'numeral', 'pre-a1', 'numbers', 'Zes stoelen in de kamer.', 'Six chairs in the room.'),
  buildVocab('vocab-pre-a1-048', 'zeven', 'seven', 'numeral', 'pre-a1', 'numbers', 'Zeven dagen in een week.', 'Seven days in a week.'),
  buildVocab('vocab-pre-a1-049', 'acht', 'eight', 'numeral', 'pre-a1', 'numbers', 'Om acht uur beginnen we.', 'We start at eight.'),
  buildVocab('vocab-pre-a1-050', 'negen', 'nine', 'numeral', 'pre-a1', 'numbers', 'Negen is mijn favoriete getal.', 'Nine is my favourite number.'),
  buildVocab('vocab-pre-a1-051', 'tien', 'ten', 'numeral', 'pre-a1', 'numbers', 'Ik tel tot tien.', 'I count to ten.'),
  buildVocab('vocab-pre-a1-052', 'elf', 'eleven', 'numeral', 'pre-a1', 'numbers', 'Om elf uur is pauze.', 'At eleven there is a break.'),
  buildVocab('vocab-pre-a1-053', 'twaalf', 'twelve', 'numeral', 'pre-a1', 'numbers', 'Twaalf maanden in een jaar.', 'Twelve months in a year.'),
  buildVocab('vocab-pre-a1-054', 'twintig', 'twenty', 'numeral', 'pre-a1', 'numbers', 'Ik ben twintig jaar.', 'I am twenty years old.'),
  buildVocab('vocab-pre-a1-055', 'dertig', 'thirty', 'numeral', 'pre-a1', 'numbers', 'Half dertig minuten fietsen.', 'Thirty minutes of cycling.'),
  buildVocab('vocab-pre-a1-056', 'honderd', 'hundred', 'numeral', 'pre-a1', 'numbers', 'Honderd euro is veel geld.', 'One hundred euros is a lot of money.'),
  buildVocab('vocab-pre-a1-057', 'maandag', 'Monday', 'noun', 'pre-a1', 'time', 'Maandag heb ik les.', 'On Monday I have class.', { article: 'de', plural: 'maandagen' }),
  buildVocab('vocab-pre-a1-058', 'dinsdag', 'Tuesday', 'noun', 'pre-a1', 'time', 'Dinsdag ga ik sporten.', 'On Tuesday I exercise.', { article: 'de', plural: 'dinsdagen' }),
  buildVocab('vocab-pre-a1-059', 'woensdag', 'Wednesday', 'noun', 'pre-a1', 'time', 'Woensdag is marktdag.', 'Wednesday is market day.', { article: 'de', plural: 'woensdagen' }),
  buildVocab('vocab-pre-a1-060', 'donderdag', 'Thursday', 'noun', 'pre-a1', 'time', 'Donderdag werk ik thuis.', 'On Thursday I work from home.', { article: 'de', plural: 'donderdagen' }),
  buildVocab('vocab-pre-a1-061', 'vrijdag', 'Friday', 'noun', 'pre-a1', 'time', 'Vrijdag drinken we koffie.', 'On Friday we drink coffee.', { article: 'de', plural: 'vrijdagen' }),
  buildVocab('vocab-pre-a1-062', 'zaterdag', 'Saturday', 'noun', 'pre-a1', 'time', 'Zaterdag slaap ik uit.', 'On Saturday I sleep in.', { article: 'de', plural: 'zaterdagen' }),
  buildVocab('vocab-pre-a1-063', 'zondag', 'Sunday', 'noun', 'pre-a1', 'time', 'Zondag rusten we uit.', 'On Sunday we rest.', { article: 'de', plural: 'zondagen' }),
  buildVocab('vocab-pre-a1-064', 'januari', 'January', 'noun', 'pre-a1', 'time', 'In januari is het koud.', 'In January it is cold.'),
  buildVocab('vocab-pre-a1-065', 'juli', 'July', 'noun', 'pre-a1', 'time', 'In juli gaan veel mensen op vakantie.', 'In July many people go on holiday.'),
  buildVocab('vocab-pre-a1-066', 'datum', 'date', 'noun', 'pre-a1', 'time', 'Wat is de datum vandaag?', 'What is today\'s date?', { article: 'de', plural: 'data' }),
  buildVocab('vocab-pre-a1-067', 'uur', 'hour / o clock', 'noun', 'pre-a1', 'time', 'Het is drie uur.', 'It is three o clock.', { article: 'het', plural: 'uren' }),
  buildVocab('vocab-pre-a1-068', 'minuut', 'minute', 'noun', 'pre-a1', 'time', 'Een minuut heeft zestig seconden.', 'A minute has sixty seconds.', { article: 'de', plural: 'minuten' }),
  buildVocab('vocab-pre-a1-069', 'half', 'half (past/to)', 'adverb', 'pre-a1', 'time', 'Het is half acht.', 'It is half past seven.', { notes: 'Dutch half eight = 7:30.' }),
  buildVocab('vocab-pre-a1-070', 'kwart over', 'quarter past', 'phrase', 'pre-a1', 'time', 'Kwart over twee.', 'Quarter past two.'),
  buildVocab('vocab-pre-a1-071', 'kwart voor', 'quarter to', 'phrase', 'pre-a1', 'time', 'Kwart voor tien.', 'Quarter to ten.'),
  buildVocab('vocab-pre-a1-072', 'vandaag', 'today', 'adverb', 'pre-a1', 'time', 'Vandaag oefenen we klanken.', 'Today we practise sounds.'),
  buildVocab('vocab-pre-a1-073', 'morgen', 'tomorrow', 'adverb', 'pre-a1', 'time', 'Tot morgen!', 'See you tomorrow!'),
  buildVocab('vocab-pre-a1-074', 'klas', 'class', 'noun', 'pre-a1', 'classroom', 'De klas begint stil te worden.', 'The class is getting quiet.', { article: 'de', plural: 'klassen' }),
  buildVocab('vocab-pre-a1-075', 'boek', 'book', 'noun', 'pre-a1', 'classroom', 'Open je boek op pagina vijf.', 'Open your book on page five.', { article: 'het', plural: 'boeken' }),
  buildVocab('vocab-pre-a1-076', 'pen', 'pen', 'noun', 'pre-a1', 'classroom', 'Ik schrijf met een blauwe pen.', 'I write with a blue pen.', { article: 'de', plural: 'pennen' }),
  buildVocab('vocab-pre-a1-077', 'oefenen', 'to practise', 'verb', 'pre-a1', 'classroom', 'We oefenen elke dag een beetje.', 'We practise a little every day.'),
  buildVocab('vocab-pre-a1-078', 'luisteren', 'to listen', 'verb', 'pre-a1', 'classroom', 'Luister naar de uitspraak.', 'Listen to the pronunciation.'),
  buildVocab('vocab-pre-a1-079', 'herhalen', 'to repeat', 'verb', 'pre-a1', 'classroom', 'Kun je dat herhalen?', 'Can you repeat that?'),
  buildVocab('vocab-pre-a1-080', 'langzaam', 'slowly', 'adverb', 'pre-a1', 'classroom', 'Spreek alsjeblieft langzaam.', 'Please speak slowly.'),
];
